### ISSUE TITLE
> Если вы работаете в Windows, то требуется установить виртуальную машину.

### ISSUE THREAD

**Issue by rivetweb** [bitrixdock/bitrixdock#1]
для виртуальной машины сейчас есть полноценные готовые настроенные образы от разработчиков битрикс.

как работать без виртуальной машины с этим докер-окружением?

**Comment by vmpartner** [comment]
Виртуальная машина от разработчиков битрикс решает ту же задачу, что и BitrixDock - предоставляет готовое окружение. Разница лишь в том, что Docker намного удобнее, проще и легче в поддержке.

Как только вы запускаете виртуалку, Docker сервисы автоматически стартуют, т.е. вы запускаете свой минихостинг для проекта и он сразу доступен.

Если у вас появится новый проект и поменяется окружение, достаточно скопировать чистую виртуалку, скопировать папку BitrixDock, добавить или заменить сервисы и запустить.

PS
Виртуальная машина от разработчиков битрикс на Apache, а у нас на Nginx, а он работает намного быстрее и кушает меньше памяти.
