### ISSUE TITLE
Время СУБД отличается от времени бекенда на 10800 секунд

### ISSUE THREAD

**Issue by niksamokhvalov** [bitrixdock/bitrixdock#10]
Спасибо за проект, хорошая работа 👍 

Настройки → Инструменты → Проверка системы: http://take.ms/SkXeg

**Comment by pavletto** [comment]
Запускаешь под Windows?

**Comment by niksamokhvalov** [comment]
Да. 11:14, 15 декабря 2017 г., Pavel Sukhodolski <notifications@github.com>:Запускаешь под Windows?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by mikhailsidorov** [comment]
Если проблема еще актуальна попробуйте подключиться к запущеным контейнерам, используя команду docker exec -ti container_id sh и сравнить время и часовой пояс. Если проблему удалось решить, пожалуйста опишите как решали проблему.

**Comment by identw** [comment]
По умолчанию используется UTC и синхронизации как я понимаю с NTP серверами нет.
