### ISSUE TITLE
Как поменять версию mysql? 

### ISSUE THREAD

**Issue by mybeenfo** [bitrixdock/bitrixdock#101]
Как поменять версию mysql? Сейчас устанавливается 8 а мне нужна 5,6. Когда переключаю в bitrixdock/mysql/Dockerfile  
с FROM mysql:8.0 FROM mysql:5.6 получаю ошибку https://i.imgur.com/3uOWnCl.png

**Comment by FaritSlv** [comment]
> Как поменять версию mysql? Сейчас устанавливается 8 а мне нужна 5,6. Когда переключаю в bitrixdock/mysql/Dockerfile
> с FROM mysql:8.0 FROM mysql:5.6 получаю ошибку https://i.imgur.com/3uOWnCl.png

Так у Вас просто ошибка подключения в битриксе, покажите контейнеры которые подгрузились.
Лог билда контейнеров

**Comment by mybeenfo** [comment]
https://i.imgur.com/R9mBuOQ.png
https://i.imgur.com/G7AlZGX.png

**Comment by vmpartner** [comment]
Может рестартануть php после того как mysql запустился, может тупо не видит
новый mysql контейнер

пн, 10 авг. 2020 г. в 14:59, mybeenfo <notifications@github.com>:

**Comment by mybeenfo** [comment]
Сделал docker restart db
https://i.imgur.com/XiF2api.png
Не помогло

А может быть есть где то старая версия с mysql 5.7 ?

**Comment by vmpartner** [comment]
Скрин конфига пжл
Там должно стоять db в имени хоста mysql

пн, 10 авг. 2020 г. в 16:18, mybeenfo <notifications@github.com>:

**Comment by vmpartner** [comment]
Пропингуйте из php fpm контейнер db, скрин сюда

пн, 10 авг. 2020 г. в 16:25, Виталий Мусин <vmpartner@gmail.com>:

**Comment by mybeenfo** [comment]
Конфиг в битриксе 
https://i.imgur.com/ea0pCSX.png
https://i.imgur.com/Imjtqz7.png
Простите, я не знаю как пинговать из php fpm контейнер db

**Comment by vmpartner** [comment]
У вас база рестартуется похоже постоянно. Конфиг в порядке.

пн, 10 авг. 2020 г. в 16:35, mybeenfo <notifications@github.com>:

**Comment by vmpartner** [comment]
Смотрите по ней логи docker logs -f db

пн, 10 авг. 2020 г. в 16:43, Виталий Мусин <vmpartner@gmail.com>:

**Comment by mybeenfo** [comment]
Сделал docker logs -f db
[log.txt](https://github.com/bitrixdock/bitrixdock/files/5050661/log.txt)

**Comment by vmpartner** [comment]
Похоже проблема в том что папка была не пустая когда вы поменяли базу,
нужно было сначала удалить volume.
Сейчас остановите и удалите контейнер с базой, удалите volume, затем
запустите всё заново

пн, 10 авг. 2020 г., 16:57 mybeenfo <notifications@github.com>:

**Comment by mybeenfo** [comment]
Большое спасибо! Да удалил docker volume и контейнеры. Запустил, всё заработало!

**Comment by vmpartner** [comment]
И вам спасибо 😉
