### ISSUE TITLE
Issue on Tasks

### ISSUE THREAD

**Issue by zazizou** [bitrixdock/bitrixdock#107]
I have just installed "bitirxdock" using your standard settings and recommendation and everything seems working fine, except for TASKS.

Unfortunately, I can not manage Tasks, instead I have this message : 

> The script encountered an error and will be aborted. To view extended error messages, enable this feature in .settings.php.
![Screenshot_2020-09-18 My tasks](https://user-images.githubusercontent.com/17546468/93637587-1bafd280-f9f6-11ea-979b-9b35ad86774c.png)

**Comment by konstantin-3l** [comment]
@zazizou can you set debug option true in bitrix/.settingss.php to see what's wrong?

**Comment by vmpartner** [comment]
Please send merg request

вт, 27 окт. 2020 г., 12:47 Tkachuk Konstantin <notifications@github.com>:
