### ISSUE TITLE
xdebug.remote_host

### ISSUE THREAD

**Issue by AndreyChursin** [bitrixdock/bitrixdock#112]
Всё отлично установилось, большое спасибо за сборку! Но вот не получается организовать работу xdebug 

Что нужно указывать в xdebug.remote_host ?

**Comment by ReWiG** [comment]
localhost пробовали?

**Comment by vmpartner** [comment]
Нужно использовать remote_back

пт, 20 нояб. 2020 г., 10:45 ReWiG <notifications@github.com>:
