### ISSUE TITLE
db  error

### ISSUE THREAD

**Issue by zaleev** [bitrixdock/bitrixdock#115]
Successfully built 35e1c9d667cc
Successfully tagged bitrixdock_web_server:latest
Starting source ... done
Starting db     ...
Starting db     ... error

ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/etc/localtime" to rootfs at "/var/lib/docker/overlay2/a2a7734b70a9016bd4c5a1db0f9eeca77d2302a1ed2d0a9fffcea1bb0e4a29fd/merged/usr/share/zoneinfo/UCT" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type    

ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/etc/localtime" to rootfs at "/var/lib/docker/overlay2/a2a7734b70a9016bd4c5a1db0f9eeca77d2302a1ed2d0a9fffcea1bb0e4a29fd/merged/usr/share/zoneinfo/UCT" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type    
ERROR: Encountered errors while bringing up the project.
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c docker-compose -f "docker-compose.yml" up -d --build" terminated with exit code: 1.

**Comment by vmpartner** [comment]
Добрый день! Для windows версии в описании есть пометка что нужно убрать
/etc/localtime

пн, 14 дек. 2020 г. в 21:12, zaleev <notifications@github.com>:
