### ISSUE TITLE
Проблема с контенером source

### ISSUE THREAD

**Issue by AndreyBuinovskiy** [bitrixdock/bitrixdock#123]
Он стартует и сразу же завершаеться. при этом при переходе в локал хост скачиваеться какойто файл вместо того чтобы открыть сайт

**Comment by paskal** [comment]
Работало ли какое-то время назад, или это чистая установка? Установлены ли файлы bitrix в директорию, где они должны находиться?
Если файлов bitrix ещё нет, это может быть проблема в конфигурации nginx с отдачей стандартного index.html, я проверю этот сценарий.

**Comment by AndreyBuinovskiy** [comment]
Изначально ставил работало. после чего поменял пути чтоб хранилось в другом месте. тоже работало, а потом перестало работать. после чего удалял все образы и все файлы заново устанавливал, но ничего не помогало.
![image](https://user-images.githubusercontent.com/61779802/103704291-1df46780-4fba-11eb-89a8-eddc3193a62b.png)

**Comment by paskal** [comment]
Source и не должен запускаться, однако то, что сайт не работает - реальная проблема, и она заключается в чём-то ином. Нужно позапускать разные более ранние коммиты чем последний, и найти, после какого перестало работать - я думаю, это связано с совсем недавними изменениями.
Я смогу потестировать только завтра вечером.

**Comment by AndreyBuinovskiy** [comment]
Судя по всему ваш комит был последним. но это было 10 дней назад поэтому не думаю что именно в нем проблема. но все же попробую откаться.
![image](https://user-images.githubusercontent.com/61779802/103739342-89fcbd00-5006-11eb-9c20-5139c63bc869.png)

**Comment by paskal** [comment]
Проблема будет решена в #124, как временное решение в файле `nginx/conf/default.conf` удалите `http2` из двух строк в начале, и переподните контейнер - всё заработает. Я совсем забыл, что http2 не работает без SSL.

**Comment by AndreyBuinovskiy** [comment]
типа потому что нет сертификата? или что? я просто только начал изучать докер и хочу понимать в чем дело. Если не сложно обьясните пожалуйста

**Comment by paskal** [comment]
Тут дело не в докере, а в nginx.

Контейнер source предназначен только для того, чтобы у всех контейнеров был одинаковый доступ к перечисленным в его определении файлам и папкам, поэтому это нормально, что он запускается и тут же умирает.

При открытии http://localhost в браузере скачивался пустой файл. Вот, что я увидел, когда сделал запрос с помощью curl:

```
$ curl -I http://localhost/index.html
curl: (8) Weird server reply
$ curl -v http://localhost/index.html
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET /index.html HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
>
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 57)
* Closing connection 0
```

В коммите 8ff466d69c7e37b64b7d23efca3c26fb1406804e поменялся конфиг nginx. Я откатывал разные файлы и их части, пока не нашёл ту, из-за которой проявлялась проблема: строка `listen 80 default;` поменялась на `listen 80 deferred http2 reuseport default;`, и при возвращении её в предыдущее состояние сайт вновь начинал работать.

Я возвращал опции listen обратно по одной, пока не увидел, что проблема возникает при добавлении `http2`, и я понял, что дело в том, что [http2 работает только с HTTPS](https://en.wikipedia.org/wiki/HTTP/2#Encryption): nginx необходим набор опций для созданиия безопасного соединения с клиентом и порт 443, чтобы это заработало корректно.

Если остались какие-либо вопросы - пожалуйста, напишите.

**Comment by vmpartner** [comment]
Тоже забыл про сертификат ). Правки принял в мастер

ср, 6 янв. 2021 г., 13:44 Dmitry Verkhoturov <notifications@github.com>:

**Comment by AndreyBuinovskiy** [comment]
> Тут дело не в докере, а в nginx.
> 
> Контейнер source предназначен только для того, чтобы у всех контейнеров был одинаковый доступ к перечисленным в его определении файлам и папкам, поэтому это нормально, что он запускается и тут же умирает.
> 
> При открытии http://localhost в браузере скачивался пустой файл. Вот, что я увидел, когда сделал запрос с помощью curl:
> 
> ```
> $ curl -I http://localhost/index.html
> curl: (8) Weird server reply
> $ curl -v http://localhost/index.html
> *   Trying ::1...
> * TCP_NODELAY set
> * Connected to localhost (::1) port 80 (#0)
> > GET /index.html HTTP/1.1
> > Host: localhost
> > User-Agent: curl/7.64.1
> > Accept: */*
> >
> Warning: Binary output can mess up your terminal. Use "--output -" to tell
> Warning: curl to output it to your terminal anyway, or consider "--output
> Warning: <FILE>" to save to a file.
> * Failed writing body (0 != 57)
> * Closing connection 0
> ```
> 
> В коммите [8ff466d](https://github.com/bitrixdock/bitrixdock/commit/8ff466d69c7e37b64b7d23efca3c26fb1406804e) поменялся конфиг nginx. Я откатывал разные файлы и их части, пока не нашёл ту, из-за которой проявлялась проблема: строка `listen 80 default;` поменялась на `listen 80 deferred http2 reuseport default;`, и при возвращении её в предыдущее состояние сайт вновь начинал работать.
> 
> Я возвращал опции listen обратно по одной, пока не увидел, что проблема возникает при добавлении `http2`, и я понял, что дело в том, что [http2 работает только с HTTPS](https://en.wikipedia.org/wiki/HTTP/2#Encryption): nginx необходим набор опций для созданиия безопасного соединения с клиентом и порт 443, чтобы это заработало корректно.
> 
> Если остались какие-либо вопросы - пожалуйста, напишит


С этим понятно, спасибо.
а скажите пожалуйста вот я сейчас развернул один проект на вашем докере. теперь чтоб развернуть второй мне заново надо все клонировать? и при этом еще зайди в админер чтоб там создать еще одну базу данных? и можно ли как то сделать чтоб оба сайта были доступны без перестройки докер контейнеров.

**Comment by vmpartner** [comment]
Чтобы было несколько проектов желательно использовать оркестратор, самый
популярный kubernetes. На Docker compose нужно вручную следить чтобы не
пересекались порты у контейнеров и сети.

ср, 6 янв. 2021 г., 18:39 Andrei Buinovskii <notifications@github.com>:

**Comment by paskal** [comment]
@AndreyBuinovskiy когда опубликую свой конфиг, там можно будет посмотреть пример, как иметь два сайта в одном docker-compose. Общая идея - нужно создать ещё один контейнер с php со своим, отдельным набором файлов, в adminer создать ещё одну базу, и создать новый конфиг для nginx для поддержки этого нового сайта.

**Comment by AndreyBuinovskiy** [comment]
Спасибо я понял. мне как начинающему этот путь еще много в чем разбираться придется. ПОтому что на словах все понятно а вот как делать начну походу офигею. 
@paskal с нетерпением жду конфига, чтоб хоть посмотреть что да как там. МОжет посоветуете что посмотреть и почитать чтоб более или менее разобраться в этом. я пока смутно понимаю принцип этого всего

**Comment by AndreyBuinovskiy** [comment]
@vmpartner я боюсь что если я еще сейчас и за кубернет с схвачусь то сделаю себе кашу в голове. но в блакнотик запишу может руки дойдут до этого.

**Comment by paskal** [comment]
kubernetes - слишком сложная штука для такой задачи, из пушки по воробьям. Я постараюсь на этой неделе причесать и опубликовать свой docker-compose.

**Comment by AndreyBuinovskiy** [comment]
@paskal, а можно ли как то в гите хранить докер компос файл чтоб таскать его за собой для быстрого развертывания. чтоб не таскать за собой еще и вот эти все файлы? 
![image](https://user-images.githubusercontent.com/61779802/103871434-175f1080-50de-11eb-9e17-996c50e17273.png)

**Comment by AndreyBuinovskiy** [comment]
@paskal, а может можно вам куда то вопросы в личные сообщения задавать?

**Comment by vmpartner** [comment]
Можно если всё запаковать в свои образы. Для этого есть приватные регистры
образов, например gitlab

чт, 7 янв. 2021 г., 13:49 Andrei Buinovskii <notifications@github.com>:

**Comment by vmpartner** [comment]
У меня обычно время нет свободного. Пока праздники отвечаю )

чт, 7 янв. 2021 г., 13:49 Andrei Buinovskii <notifications@github.com>:

**Comment by AndreyBuinovskiy** [comment]
@vmpartner, и на этом спасибо. я просто хочу перейти на локальную разработку. а то все пока что по старинке, либо прям на боевом либо один дев сервер на всех. но пока не знаю как уйти. вот пробую различные способы.  может что то подскажите или направите?

**Comment by paskal** [comment]
@AndreyBuinovskiy напиши мне на http://t.me/paskal_07.

**Comment by paskal** [comment]
Для истории, я опубликовал docker-compose своего сайта тут:  https://github.com/paskal/favor-group.ru
