### ISSUE TITLE
kdevtmpfsi майнер в docker image

### ISSUE THREAD

**Issue by kl09** [bitrixdock/bitrixdock#125]
Заметил очень странное, процесс `/tmp/kdevtmpfsi` сжирал CPU под 100% на протяжение месяца, заметил только сейчас.

Очень похоже что он запускался из под докера, из php7.1, из этого image: 
`FROM bitrixdock/php71-fpm:latest`

При docker kill этого контейнера - майнер умирал.

**Comment by Slach** [comment]
нет =) он через ваше приложение пущеное в инет и инъекцию в php \ bitrix ставился как процесс в системе
то что он умирал после docker pull и рестарте контейнера как раз говорит о том, что это внешнее заражение

**Comment by kl09** [comment]
не думаю что инъекция, смена образа помогла.

**Comment by Slach** [comment]
ну ждите когда в следующий раз сканер придет -)
но тут тоже может быть что смена образа закрыла уязвимость в php которая эксплуатировалась через ваше приложение

**Comment by kl09** [comment]
Не думаю что кто то из вне дергал: перезапуск сервера, перезапуск контейнера - майнер умирал и 2-3 минуты спустя он поднимался. 
Смена образа на ту же версию php помогла.
+ в логах nginx нету ничего подозрительного

**Comment by vmpartner** [comment]
Я уже сталкивался с этим, проблема в открытом 9000 порту в php контейнере.

вс, 10 янв. 2021 г., 21:51 Isaev Ivan <notifications@github.com>:

**Comment by Slach** [comment]
@vmpartner может тогда имеет смысл обновить образы? 
phpdockerio образы на базе которых сделан bitrixdock сейчас статусе  Deprecared

https://hub.docker.com/r/phpdockerio/php71-fpm
DEPRECATED
This image is now deprecated and not built daily due to EOL reached on both PHP and the base image OS (Debian Jessie).

**Comment by vmpartner** [comment]
Время нет. Принимаю пул реквесты )
Образы к тому же не помогут. Нужно в docker-compose не открывать 9000 порт.
В нашем репозитории давно закрыл.

пн, 11 янв. 2021 г., 11:48 Eugene Klimov <notifications@github.com>:
