### ISSUE TITLE
mysql:8.0 приводит к ошибке при установке на ARM64 

### ISSUE THREAD

**Issue by voromax** [bitrixdock/bitrixdock#130]
Платформа: Raspberry Pi 4 Ubuntu 64 bit

при попытке проинсталлировать с помощью install.sh скрипт вылетает со следующей ошибкой:

```
...

Building db
Sending build context to Docker daemon  3.072kB

Step 1/5 : FROM mysql:8.0
8.0: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR: Service 'db' failed to build

```

Возможно mysql:8.0 - не лучший выбор?

**Comment by vmpartner** [comment]
Ставить Битрикс на raspberry очень оптимистично. Мне кажется эта авантюра
изначально обречена на провал )

вс, 21 мар. 2021 г., 04:10 voromax ***@***.***>:

**Comment by vmpartner** [comment]
Я думаю работать конечно будет, но всё же скорость будет очень низкая

вс, 21 мар. 2021 г. в 15:59, Виталий Мусин ***@***.***>:

**Comment by vmpartner** [comment]
Вот здесь нашли какое то решение, попробуйте:
https://github.com/docker-library/mysql/issues/318#issuecomment-783340346

вс, 21 мар. 2021 г. в 17:00, Виталий Мусин ***@***.***>:

**Comment by voromax** [comment]
Но это может быть и Ваш маленький монстр Apple Mac Mini M1... Попробую mysql:5.7 или MarinaDB. О результатах отпишусь. 

... И не нужно малышку малинку недооценивать ;-)

**Comment by vmpartner** [comment]
Ну да, m1 другой разговор

вс, 21 мар. 2021 г., 17:47 voromax ***@***.***>:

**Comment by paskal** [comment]
Теперь эта issue может быть закрыта.

**Comment by voromax** [comment]
В качестве альтернативы можно также добавить опцию выбора marinadb при установке
