### ISSUE TITLE
Доработал проект (поддержка нескольких сайтов, SSL сертификаты от Letsencrypt)

### ISSUE THREAD

**Issue by dev-bitrix** [bitrixdock/bitrixdock#131]
Всем привет, понравилась сборка с данной репы и я решил доработать немного ее и добавить пару возможностей

https://github.com/darbit-ru/bitrix_docker - вот ссылка на мою версию
В ней есть возможность установки нескольких сайтов, добавление SSL сертификата и т.д.
В описании есть видео демонстрации.

Для себя сборку делал чтобы проекты разворачивать или локально тестовые сайты быстро поднимать.
Использую в работе ElasticSearch по этому и она устанавливается.
Есть планы доработки под sphinx и smtp

Прошу любить и жаловать)

**Comment by Slach** [comment]
Обычно в таких случаях обычно используют такую вещь как fork, а не создают репозиторий с нуля и стараются просто сделать pull request в исходный проект =)

**Comment by dev-bitrix** [comment]
ну сборку делал для себя, да и еще в этой репе написано что она только для запуска демки

![image](https://user-images.githubusercontent.com/12772140/112586874-c3cfa980-8e26-11eb-8b27-d3da81706fcc.png)

считайте что этот проект как один из продакшн проектов с дополнительными функциями, которую сделал для себя, для удобства. Ато вымораживает каждый проект создавать nginx конф, бд, перезапускать сервисы и т.д. Ранее работал на чистом Centos где сделал сборку nginx + php-fpm + mysql + memcache + es
