### ISSUE TITLE
Нет MySQL

### ISSUE THREAD

**Issue by maratkh** [bitrixdock/bitrixdock#132]
После установки автоматическим режимом, пишет чт в php нет MysQL
![image](https://user-images.githubusercontent.com/3676774/112613320-04ccbb80-8e31-11eb-89e2-74f876c25a6e.png)

**Comment by dev-bitrix** [comment]
покажите состояние докер контейнеров

```cd /var/www/bitrixdock/ && docker ps```

скрин сделайте и выложите

**Comment by paskal** [comment]
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/712534/113076969-79587f00-91d0-11eb-8561-41bfe160e33b.png">
Не смог воспроизвести. Ошибка где-то в контейнере mysql, смотрите логи: `docker-compose logs --tail 300 db`
