### ISSUE TITLE
docker-compose up -d

### ISSUE THREAD

**Issue by glasscat82** [bitrixdock/bitrixdock#136]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.db: 'platform'

**Comment by pavletto** [comment]
Вероятно, что вы используете старую версию `docker-compose`, которая не поддерживает формат 2 версии. Попробуйте обновить docker-compose

**Comment by glasscat82** [comment]
"--platform" is only supported on a Docker daemon with experimental features enabled
ERROR: Service 'db' failed to build : Build failed

docker --version
Docker version 18.09.1, build 4c52b90

docker-compose --version
docker-compose version 1.29.2, build 5becea4c

**Comment by glasscat82** [comment]
сборка работает на последних только версиях docker с включенными  экспериментальными функциями
 Experimental:      true
а как включить эти функции,человек должен потратить уйму времени! Даже КОТА не покормишь

**Comment by glasscat82** [comment]
Для включения экспериментальных функций докера создайте следующий файл:
sudo nano /etc/docker/daemon.json
И добавить ниже содержание к нему
{ 
    "experimental": true 
} 

И сохраните файл (CTRL + X и Enter) и выйдите. В типе терминала:
sudo service docker restart
Чтобы проверить, включены ли экспериментальные функции, введите в терминал:
docker version
И вы должны увидеть Experimental: true
