### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by glasscat82** [bitrixdock/bitrixdock#137]
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by dev-bitrix** [comment]
При создании пользователя вместо localhost укажите *

**Comment by glasscat82** [comment]
проблема была решена полностью пестановкой новой версии 
docker   
Version:   20.10.6
и новой версии docker-compose
version 1.29.2
