### ISSUE TITLE
Apache только под AMD64

### ISSUE THREAD

**Issue by konstantin83** [bitrixdock/bitrixdock#143]
В Dockerfile апача указан image: FROM gendosu/alpine-apache:latest
Но на Macbook M1 докер ругается, что этот image только под  AMD64.
![Container list 2021-08-01 18-42-54](https://user-images.githubusercontent.com/13274062/127776951-4fecda11-1663-4b11-a275-12ab8aeffaff.jpg)

Подскажите, какой ещё можно использовать, который без тормозов работает на ARM и на Intel?

**Comment by Elnadrion** [comment]
Сейчас по дефу используется базовый образ `httpd` с поддержкой arm архитектуры, этот issue можно закрыть @vmpartner

**Comment by vmpartner** [comment]
🫡
