### ISSUE TITLE
Что я делаю не так?

### ISSUE THREAD

**Issue by Atrokirina** [bitrixdock/bitrixdock#153]
Стоит подсистема ubuntu 20 
Клонирую проект сюда /mnt/c/Users/user/domains/bitrixdock
Меняю SITE_PATH на SITE_PATH=/mnt/c/Users/user/domains/bitrixdock/www/bitrix/ , в котором уже лежит bitrixsetup
B default.conf прописываю аналогичный root.
В результате получаю постоянную ошибку: No input file specified.

**Comment by rodnyco** [comment]
По идее структура проекта должны выглядеть так:
- projectFolder
   - var
      - www
         - bitrix
               bitrixsetup
         - bitrixdock     

Попробуйте именно в такой структуре папок собрать проект

**Comment by romych97** [comment]
та же проблема. вышеупомянутое решение с изменением структуры проекта не работает

**Comment by Elnadrion** [comment]
> B default.conf прописываю аналогичный root. В результате получаю постоянную ошибку: No input file specified.

А где в доках написано, что нужно менять root в default.conf?)
Там путь относительно контейнера, его не надо менять
