### ISSUE TITLE
Ошибка восстановления базы данных

### ISSUE THREAD

**Issue by bitrixdevelop** [bitrixdock/bitrixdock#162]
После разворачивания контейнеров не использую bitrixsetup, а разворачиваю бекап с помощью restore.php. В самом конце разворачивания базы получаю ошибку:

```
Ошибка восстановления базы данных | Ошибка восстановления базы данных |  
-- | -- | --
Ошибка восстановления базы данных |  
MySQL query error!Access denied; you need (at least one of) the SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operationSET innodb_strict_mode=0

```

Может кто в курсе что я делаю не так и почему свежесозданный юзер не имеет нужных прав?

**Comment by bitrixdevelop** [comment]
Исправил путем влезания в контейнер, подключения через консоль к мусулю и заданию прав.

**Comment by NaumovEvgeniy** [comment]
@bitrixdevelop, как это сделать, можете описать, пожалуйста?

**Comment by Elnadrion** [comment]
Столкнулся с той же проблемой
На дефолтного юзера (bitrix) не хватает одной из привелегий SYSTEM_VARIABLES_ADMIN или SESSION_VARIABLES_ADMIN
Я если честно не придумал как это вкорячить в сборку контейнера, т.к. у нас динамические имя пользователя и базы

Самый простой вариант в данной ситуации - это тупо использовать root юзера, вместо bitrix

@vmpartner что думаешь по этому поводу?)

**Comment by vmpartner** [comment]
Можно попробовать прописать в инит скрипте, здесь пример https://stackoverflow.com/a/56616412

**Comment by Elnadrion** [comment]
Ок, завтра попробую найти время сделать. Можешь снова открыть issue?
Но как я уже писал выше - у нас нельзя будет прописать туда динамическое имя пользователя (MYSQL_USER из .env) т.к. это по сути обычный sql файл, он не подхватит переменную

**Comment by Elnadrion** [comment]
@bitrixdevelop @NaumovEvgeniy Есть желание потестить?)
Возможно контейнер с базой необходимо будет перебилдить
`docker compose up -d --build db`

**Comment by Elnadrion** [comment]
@vmpartner это тоже пофиксили
