### ISSUE TITLE
Есть ли конфиг yml под 3ю версию docker-compose?

### ISSUE THREAD

**Issue by KoRNeT46RuS** [bitrixdock/bitrixdock#164]
Может кто поделится? Юзаю 3.7

**Comment by FaritSlv** [comment]
> Может кто поделится? Юзаю 3.7

Вы не знаете как переделать или просто лень разбираться?

**Comment by Elnadrion** [comment]
У docker compose нет 3 версии

**Comment by FaritSlv** [comment]
> У docker compose нет 3 версии

Вы меня извините конечно 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/7736725/170717486-a01b15a0-f6db-412a-b439-fae8a7f8d345.png">

**Comment by Elnadrion** [comment]
Это версия yml файла, а не docker compose

**Comment by FaritSlv** [comment]
> Это версия yml файла, а не docker compose

Я понимаю, так это ему и нужно

**Comment by KoRNeT46RuS** [comment]
> > Может кто поделится? Юзаю 3.7
> 
> Вы не знаете как переделать или просто лень разбираться?

Не очень разбираюсь. Что-то ковырял вопросы по миграции, да не получилось

**Comment by Elnadrion** [comment]
@KoRNeT46RuS если вы запускаете проекты на версии yml файла 3.7, то вторая версия взлетит
