### ISSUE TITLE
No input file specified.

### ISSUE THREAD

**Issue by sherayzin** [bitrixdock/bitrixdock#170]
Hello. I have error with volumes or rights "No input file specified."

I just do the following steps:

1. install clean Ubuntu 22 on my pc (i tried do the same steps on ubuntu 18 (WSL))
2. install docker & git
3. make docker for use with no 'sudo' by this:
`sudo groupadd docker
sudo gpasswd -a ${USER} docker
newgrp docker`
5. install vs code with extensions 'docker' and 'remote environment'
6. makedir in /home/user/dockertest
7. in this dir i clone the repo by 
`git clone https://github.com/bitrixdock/bitrixdock.git`
9. the i make a .env
`cp .env_default .env`
11. correct it:
`COMPOSE_PROJECT_NAME=bitrixdock
PHP_VERSION=php81
WEB_SERVER_TYPE=nginx
DB_SERVER_TYPE=percona
MYSQL_DATABASE=bitrix
MYSQL_USER=bitrix
MYSQL_PASSWORD=123
MYSQL_ROOT_PASSWORD=123
INTERFACE=0.0.0.0
SITE_PATH=~/bitrix/public_html`

13. then i just tried to do make bitrixsetup.php
`make bitrix-setup`
15. after this i have bitrixsetup.php on /home/user/bitrix/public_html
16. bu after 'docker-compose up -d' i have en error on localhost:80 'No input file specified.'

whats wrong? 

BUT on Ubuntu WSL (not Ubuntu 22) i tried this and it was the same error. I`m not sure but i propably fix it with 
`chown -Rv 1000:1000 /home/user/bitrix` or something like this

but in Ubuntu 22 it was no effect

what i should do?

**Comment by sherayzin** [comment]
UPD
Solved by reinstall standart version of docker & docker compose (had to delete preinstall version)

**Comment by eydeveloper** [comment]
> UPD Solved by reinstall standart version of docker & docker compose (had to delete preinstall version)
> 
> And now i have
> 
> ` ��� ���������� ������� �������� ������. �������� ����������� ����� ������ ����� � ����� �������� [.settings.php](https://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=43&LESSON_ID=2795)`
> 
> on bitrixsetup.php at SQL base step (after entering pass db and login)
> 
> but there is no file .settings before bitrix doesnt install yet

You need to change php version from 8.1 to 8.0.
Then update the modules and revert back the php version
