### ISSUE TITLE
Постоянная загрузка при обращении к серверу

### ISSUE THREAD

**Issue by Hmarketing** [bitrixdock/bitrixdock#171]
Коллеги, доброго времени суток!

Столкнулся с проблемой, при обращении к Marketplace Битрикс получаю вечную загрузку, при тесте сервера bitrix_server_test.php файл очень долго проверяет сервер, начал копать и понял в файле bitrix_server_test.php есть кусок кода который пытается загрузить файл bitrix_server_test.php с сервера Битрикс который и тормозит скрипт:
`
if (!$_REQUEST['UPDATE_SUCCESS'] && !file_exists(dirname(__FILE__).'/bitrix_server_test.debug'))
{
	$this_script_name = basename(__FILE__);
	$bx_host = 'www.1c-bitrix.ru';
	$bx_url = '/download/files/scripts/'.$this_script_name;
	$res = @fsockopen($bx_host, 80, $errno, $errstr, 3);

	if($res) 
	{
		$strRequest = "HEAD ".$bx_url." HTTP/1.1\r\n";
		$strRequest.= "Host: ".$bx_host."\r\n";
		$strRequest.= "\r\n";

		fputs($res, $strRequest);

		while ($line = fgets($res, 4096))
		{
			if (@preg_match("/Content-Length: *([0-9]+)/i", $line, $regs))
			{
				if (filesize(__FILE__) != trim($regs[1]))
				{
					$tmp_name = $this_script_name.'.tmp';
					if ($str = file_get_contents('http://'.$bx_host.$bx_url))
					{
						if (file_put_contents(__FILE__, $str))
						{
							bx_accelerator_reset();
							echo '<script>document.location="?UPDATE_SUCCESS=Y";</script>';
							die();
						}
						else
							$strError = str_replace("#FILE#", $this_script_name, GM("LOADER_LOAD_CANT_OPEN_WRITE"));
					}
					else
						$strError = GM('LOADER_NEW_VERSION');
				}
				break;
			}
		}
		fclose($res);
	}
}`

Причем если подставить вот сюда https, все работает корректно:
`$bx_host = 'www.1c-bitrix.ru](https://www.1c-bitrix.ru/';`

**Comment by vmpartner** [comment]
У нас проект связан только с docker, никого отношения к исходникам нету к сожалению. Жаль что у Битрикса нет официального проекта на гитхабе чтобы сделать пул реквест

**Comment by Hmarketing** [comment]
Так и вопрос полностью про докер, я показал кусок кода который сильно тормозит, через ваш образ нет возможности подключится к Маркетплейсу Битрикс из админки, по всей видимости опять из за запроса к серверу Битрикс.

При этом, все корректно работает в [Open Server](https://ospanel.io/). Я хочу понять, эта проблема только у меня или у всех?
