### ISSUE TITLE
Проблемы со скоростью

### ISSUE THREAD

**Issue by romadov** [bitrixdock/bitrixdock#178]
Почему-то публичная часть вообще не прогружается, а админка работает, но иногда страницы грузятся по 5-7 минут. Скорее-всего дело в ресурсах. Но пока непонятно что поднять чтобы работало как нужно

**Comment by Elnadrion** [comment]
Проверь нет ли каких-то не асинхронных запросов запросов во внешние сервисы на прологе

+ по тикету оч мало данных, как минимум не хватает инфы про окружение
