### ISSUE TITLE
PHP7.4 / 8.0 error

### ISSUE THREAD

**Issue by doraketa** [bitrixdock/bitrixdock#183]
Приветствую!

Решил развернуть фриланс проект на базе ваших контейнеров, после указания настроек подключения к базе данных отлавливаю следующую ошибку:

![image](https://user-images.githubusercontent.com/68593780/230766965-ddc937cc-d3ee-42f5-be8c-5b68ab3976ed.png)

Думаю, тут пояснять ничего не нужно, всем и так ясно, что это за ошибка.

Мой ENV:

![Снимок экрана 2023-04-09 в 13 15 09](https://user-images.githubusercontent.com/68593780/230767199-abf1c4d5-9819-40bf-a97c-5b01aec11b43.png)

В bitrix-error.log лишь одна ошибка, которая уже была исправлена:

![image](https://user-images.githubusercontent.com/68593780/230767411-42c5d271-77a0-4260-aa6f-3d5301d7e9ad.png)

К слову, для нормальной работы php8.0 пришлось еще и редактировать конфигурацию php8.0->fpm->php.ini, и, явно указывать сохранение сессий, так как вылетала ошибка, что php не знает, куда сохранять сессию.

Уточню, re-build осуществлял, перезапуск контейнеров после билда (на всякий случай) тоже был осуществлен.

Заранее спасибо! :)

**Comment by doraketa** [comment]
Уточню, re-build осуществлял, перезапуск контейнеров после билда (на всякий случай) тоже был осуществлен.

**Comment by Elnadrion** [comment]
Привет. Покажи пожалуйста ошибку с сессиями, которая была, а так же файлы bitrix/.settings.php и bitrix/.settings_extra.php
Почему issue называется PHP7.4 / 8.0 error ? на остальных версиях нормально работает?

**Comment by doraketa** [comment]
> Привет. Покажи пожалуйста ошибку с сессиями, которая была, а так же файлы bitrix/.settings.php и bitrix/.settings_extra.php Почему issue называется PHP7.4 / 8.0 error ? на остальных версиях нормально работает?

Так назван issue по причине того, что ошибка была воспроизведена на этих версиях, могу скорректировать :)

Воспроизвести уже не получится, однако - в визарде висела красная надпись, которая не позволяла продолжить инсталляцию:

`Нет. Вероятно, каталог, используемый для сохранения параметров сессии, не доступен для записи`

Чтобы развеять все мифы насчет версии - используется лицензия, "Малый Бизнес", дистрибутив взят с оф. сайта, из личного кабинета, его версия: Малый бизнес 22.0.300

**Comment by Elnadrion** [comment]
> а так же файлы bitrix/.settings.php и bitrix/.settings_extra.php

?

**Comment by doraketa** [comment]
> > а так же файлы bitrix/.settings.php и bitrix/.settings_extra.php
> 
> ?

К сожалению, они еще не успели создаться, развертываю чистую версию, выглядит это так:

![image](https://user-images.githubusercontent.com/68593780/230767873-8ec1d448-01a2-4ca5-a0bf-8cbde8120202.png)

![image](https://user-images.githubusercontent.com/68593780/230767878-40e7ad9f-cede-4310-a313-1ce5d13835ce.png)

**Comment by doraketa** [comment]
Возможно, так будет еще точнее, в какой момент и что происходит.

https://user-images.githubusercontent.com/68593780/230768223-add11839-12fe-474f-b776-fb6cbac3ea25.mp4

**Comment by Elnadrion** [comment]
Получается это чистая установка демо битрикса?

> Решил развернуть фриланс проект

Я думал разворачиваешь существующий из бэкапа

**Comment by doraketa** [comment]
> Получается это чистая установка демо битрикса?
> 
> > Решил развернуть фриланс проект
> 
> Я думал разворачиваешь существующий из бэкапа

Виноват, не хотел вводить в заблуждение... Да, достаточно долгая история, но мне потребовался чистый образ для продолжения работы уже в нем.

**Comment by Elnadrion** [comment]
> К сожалению, они еще не успели создаться, развертываю чистую версию, выглядит это так:

bitrix/.settings.php  находится в папке bitrix 😁
Поставь там debug => true чтобы увидеть ошибку

Только что проверил на локальной установке. Все работает на 7.4, но появляется ошибка при неверном введенном пароле (только у меня с нормальной кодировкой)

Я подозреваю что возможно ты сменил пароль к базе после того, как поднял ее, а потом пытался перебилдить. В данном случае ребилд не поможет поменять креды, т.к. этот пароль сохраняется в данных базы в томе (volume). В таком случае изменить пароль можно или руками в контейнере или пересоздав образ:
`
docker compose down -v
docker compose up -d
`

Попробуй дефолтный пароль 123

**Comment by doraketa** [comment]
> > К сожалению, они еще не успели создаться, развертываю чистую версию, выглядит это так:
> 
> bitrix/.settings.php находится в папке bitrix 😁 Поставь там debug => true чтобы увидеть ошибку
> 
> Только что проверил на локальной установке. Все работает на 7.4, но появляется ошибка при неверном введенном пароле (только у меня с нормальной кодировкой)
> 
> Я подозреваю что возможно ты сменил пароль к базе после того, как поднял ее, а потом пытался перебилдить. В данном случае ребилд не поможет поменять креды, т.к. этот пароль сохраняется в данных базы в томе (volume). В таком случае изменить пароль можно или руками в контейнере или пересоздав образ:
> 
> ```
> docker compose down -v
> docker compose up -d
> ```
> 
> Попробуй дефолтный пароль 123

Да я ж знаю, где эти файлы находятся, но на этом этапе их еще нет, скрины выше, первый - из папки bitrix. Так бы уже давно дебаггинг включил.

![Снимок экрана 2023-04-09 в 14 36 32](https://user-images.githubusercontent.com/68593780/230770314-46a2f969-6640-4b55-a22b-d8127e6481f9.png)

Касательно ребилда - сейчас попробую, большое спасибо за feedback, как только закончу - постараюсь сам вернуться с обратной связью :)

**Comment by Elnadrion** [comment]
> Да я ж знаю, где эти файлы находятся, но на этом этапе их еще нет, скрины выше, первый - из папки bitrix. Так бы уже давно дебаггинг включил.

Сорян, мне показалось у меня на твоем шаге уже был создан этот файл :)

**Comment by doraketa** [comment]
> > Да я ж знаю, где эти файлы находятся, но на этом этапе их еще нет, скрины выше, первый - из папки bitrix. Так бы уже давно дебаггинг включил.
> 
> Сорян, мне показалось у меня на твоем шаге уже был создан этот файл :)

Все ок)

А вот при развертывании с нуля - аналогичная ошибка, все таки, воспроизводится :) Снова полез в php.ini от 8.0 PHP)
![image](https://user-images.githubusercontent.com/68593780/230770534-51ac4340-6c79-48f8-ba78-5957c319ba31.png)

**Comment by doraketa** [comment]
> > К сожалению, они еще не успели создаться, развертываю чистую версию, выглядит это так:
> 
> bitrix/.settings.php находится в папке bitrix 😁 Введи `ls -la` чтобы его увидеть Поставь там debug => true чтобы увидеть ошибку
> 
> Только что проверил на локальной установке. Все работает на 7.4, но появляется ошибка при неверном введенном пароле (только у меня с нормальной кодировкой)
> 
> Я подозреваю что возможно ты сменил пароль к базе после того, как поднял ее, а потом пытался перебилдить. В данном случае ребилд не поможет поменять креды, т.к. этот пароль сохраняется в данных базы в томе (volume). В таком случае изменить пароль можно или руками в контейнере или пересоздав образ:
> 
> ```
> docker compose down -v
> docker compose up -d
> ```
> 
> Попробуй дефолтный пароль 123

Так, да, теория насчет пароля оказалось верной, моя ошибка. Благодарю за решение! :)

Но вот с сессиями - грусть. Если подтвердится, могу мерж сделать :)

**Comment by Elnadrion** [comment]
> Так, да, теория насчет пароля оказалось верной, моя ошибка. Благодарю за решение! :)

Збс :)

> Но вот с сессиями - грусть. Если подтвердится, могу мерж сделать :)

Было бы отлично, у меня не было такой ошибки. Возможно как-то связано с тем, что работаешь не через WSL2

**Comment by paskal** [comment]
Эту issue вероятно можно закрыть.
