### ISSUE TITLE
Делала все по инструкции, вылезает в браузере по адресу http://127.0.0.1/index.html "No input file specified."

### ISSUE THREAD

**Issue by Smyluck** [bitrixdock/bitrixdock#185]
env дефортный:
`# Project name to separate multiple bitrixdock instances
COMPOSE_PROJECT_NAME=bitrixdock

# PHP version settings. Allowed values are: php56, php71, php73, php74, php80, php81, php82
PHP_VERSION=php74

# Web server type. Allowed value is apache or nginx.
WEB_SERVER_TYPE=nginx

# MySQL settings. Allowed value is mysql or percona.
DB_SERVER_TYPE=mysql
MYSQL_DATABASE=bitrix
MYSQL_USER=bitrix
MYSQL_PASSWORD=123
MYSQL_ROOT_PASSWORD=123

# Network
INTERFACE=0.0.0.0

# Site path
SITE_PATH=/var/www/bitrix`

и в пхпшторм  при попытке выбора cli interpreters через docker-compose.yml возникает ошибка "process docker-compose config failed. /usr/local/bin/docker-compose:1:Not: not found"

**Comment by Elnadrion** [comment]
Сайт лежит по этому адресу `SITE_PATH=/var/www/bitrix`` ?

**Comment by Smyluck** [comment]
да. причем в adminer заходит.

**Comment by Smyluck** [comment]
Небходимо исправить файл .env
`# Site path
SITE_PATH=./www/bitrix`
и добавить папку `bitrix `в папке `www` репозитория.
