### ISSUE TITLE
Проблема со сменой портов

### ISSUE THREAD

**Issue by romadov** [bitrixdock/bitrixdock#187]
Добрый день, хочу развернуть второй проект через вас, но возникает проблема со сменой портов.
Порты в докере создаются, ошибок нет, https://i.imgur.com/m04cC1b.png но при переходе возникает ошибка https://i.imgur.com/eaGv0kR.png и ссылается тут на верную папку - https://i.imgur.com/oJOGQuf.png которая есть в системе - https://i.imgur.com/uAGzYjJ.png
Подскажите, в чем может быть причина? Я менял их в docker-compose.yml, менял и в файлах Dockerfile там где EXPOSE... может еще где-то нужно поменять чтобы запустилось?

**Comment by Elnadrion** [comment]
Привет
А у тебя веб сервер внутри слушает порты 4444 и 811?

**Comment by romadov** [comment]
Я там уже менял везде на 4344 и 821
Вот как сейчас - https://i.imgur.com/sxDxDgH.png
И тут - https://i.imgur.com/HmSsdb9.png
и тут - https://i.imgur.com/vBpIFng.png

**Comment by romadov** [comment]
все понял) спасибо, моя невнимательность
