### ISSUE TITLE
Получение актуальных доступов для подключения к базе данных через Workbench

### ISSUE THREAD

**Issue by romadov** [bitrixdock/bitrixdock#188]
Добрый день, а могли бы вы подсказать, как можно получить актуальные доступы для подключения к бд?
Сейчас прописано так - https://i.imgur.com/413mZu0.png и тут так https://i.imgur.com/yOYLzD5.png
Ввожу в workbecnh так - https://i.imgur.com/kr59iLI.png и пишет - https://i.imgur.com/tAj4YJu.png. Спасибо заранее

**Comment by romadov** [comment]
если правильно смотрю то так - https://i.imgur.com/jNfGqPO.png

**Comment by Elnadrion** [comment]
У тебя база слушает дефолтный 3306 порт. Тебе нужно маппить или его или форвардить 3316 на 3306

> https://i.imgur.com/413mZu0.png

```yaml
ports:
  - ${INTERFACE}:3316:3306
```

**Comment by romadov** [comment]
спасибо большое!

**Comment by romadov** [comment]
А может еще сталкивались - если на любом инфоблоке будь то раздел или элемент - no imput file specified?

**Comment by paskal** [comment]
Эту issue вероятно можно закрыть.
