### ISSUE TITLE
Автоматическая установка

### ISSUE THREAD

**Issue by Strepsils1337** [bitrixdock/bitrixdock#190]
`curl -fsSL https://raw.githubusercontent.com/bitrixdock/bitrixdock/master/install.wsl.sh?$(date +%s) -o install.wsl.sh && chmod +x install.wsl.sh && sh install.wsl.sh` использую установщик, выдаёт ошибку:
Create folder struct
install.wsl.sh: 8: install.wsl.sh: wget: not found
cp: cannot stat '/var/www/bitrixdock/.env_template': No such file or directory
исполюзую Docker Desctop

**Comment by paskal** [comment]
Эту issue можно закрыть, исправлено.
