### ISSUE TITLE
RU LANG is not available in Ubuntu 20.04

### ISSUE THREAD

**Issue by Froz10** [bitrixdock/bitrixdock#195]
Собирал вручную на Ubuntu 20.04, не отображался RU. Необходимо было установить Битрикс Управление сайтом.
Захардкодил RU в файле bitrixsetup.php, но так не должно быть, я думаю.
![image](https://github.com/bitrixdock/bitrixdock/assets/45262181/175ba8ad-237e-4b78-b236-289d41658153)
![image](https://github.com/bitrixdock/bitrixdock/assets/45262181/4fde1c4f-9c98-48c7-8b9f-08329d8977fe)

**Comment by Elnadrion** [comment]
Мы не обслуживаем bitrixsetup.php, его обслуживают битриксоиды
Как и где вы его скачали изначально?

**Comment by Froz10** [comment]
Понятно, да, немного не по адресу, пардон. Скачивал с оф. сайта, самую последнюю версию.
