### ISSUE TITLE
restore.php Введен неверный пароль

### ISSUE THREAD

**Issue by cron532** [bitrixdock/bitrixdock#197]
Добрый день. 
При попытке развернуть битрикс из резервной копии (архив с копией лежит в корне битрикса) ругается на неправильный пароль. Проблема в том, что пароль верный. Успешно развернул эту же копию на виртуальной машине от самого битрикса. Пробовал так же на другом компьютере развернуть ту же резервную копию в bitrixdoc, тоже ругнулся на неверный пароль.

Пишу сюда, ибо гугл не особо помог.

**Comment by Elnadrion** [comment]
Какой пароль? От базы?

**Comment by cron532** [comment]
> Какой пароль? От базы?

Пароль от резервной копии.

**Comment by auponomarev** [comment]
> При попытке развернуть битрикс из резервной копии (архив с копией лежит в корне битрикса) ругается на неправильный пароль. 

В докер контейнере нужно включить опцию. 

sed -i '/^default = default_sect/a legacy = legacy_sect' /etc/ssl/openssl.cnf
sed -i '/^\[default_sect\]/a activate = 1' /etc/ssl/openssl.cnf
printf "[legacy_sect]\nactivate = 1" >> /etc/ssl/openssl.cnf

Взято отсюда. 
https://stackoverflow.com/questions/73832854/php-openssl-pkcs12-read-error0308010cdigital-envelope-routinesunsupported
