### ISSUE TITLE
Проблема Mysqli

### ISSUE THREAD

**Issue by KornetWeb** [bitrixdock/bitrixdock#205]
С ветки master разворачивал на версии 7.4. Ругается на 
`Call to undefined function mysqli_init()`

Смотрел через phpinfo нет модуля. Пробовал установить - установка проходит, но модуля нет.

**Comment by Elnadrion** [comment]
Проверил на чистом контейнере с 7.4:
![image](https://github.com/bitrixdock/bitrixdock/assets/33313896/35f893d7-cf17-43d0-b384-8d1b8c067d8d)

**Comment by KoRNeT46RuS** [comment]
У меня вывод такой,
`root@28a65a9eba80:/var/www/bitrix# php -m

Warning: PHP Startup: Unable to load dynamic library 'mcrypt' (tried: /usr/lib/php/20190902/mcrypt (/usr/lib/php/20190902/mcrypt: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/mcrypt.so (/usr/lib/php/20190902/mcrypt.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
[PHP Modules]
apc
apcu
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

root@28a65a9eba80:/var/www/bitrix# 
`

Хотя исходя из докерфайла ставиться должен
`FROM phpdockerio/php:7.4-fpm

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
    mc \
    php7.4-gd \
    php7.4-imagick \
    php7.4-intl \
    php7.4-interbase \
    php7.4-mbstring \
    php7.4-mcrypt \
    php7.4-memcache \
    php7.4-memcached \
    php7.4-mysql \
    php7.4-mysqli \
    php7.4-pdo \
    php7.4-opcache \
    php7.4-soap \
    php7.4-xdebug \
    php7.4-zip \
    php7.4-pear \
    php7.4-pdo-mysql \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
`

**Comment by paskal** [comment]
Непонятная ситуация, но я думаю что это сочетание config.php в котором указано подключение модуля mcrypt, и образа в котором установлен пакет `php7.4-mcrypt`, что подразумевает что отдельно указывать этот модуль в config.php нельзя. Я думаю, если это сделать, ломаться будет как раз с описанными здесь симптомами.

Я подозревал об этой проблеме, поскольку изменение типа установки mcrypt сломало обратную совместимость: надеюсь, на это наткнулось не так много людей и они разобрались что делать.

Если вы вдруг видите эту проблему, попробуйте удалить упоминание mcrypt из своего config.php.

**Comment by KornetWeb** [comment]
Все заработало
