### ISSUE TITLE
Установка для Windows (CMD/PowerShell)

### ISSUE THREAD

**Issue by webnetkz** [bitrixdock/bitrixdock#222]
Необходимо добавить установку для windows пользователей, которые не используют WSL.

**Comment by FelemixX** [comment]
docker compose up -d --build так же работает при включенном докере с интеграцией через hyper-v

**Comment by paskal** [comment]
@webnetkz, @FelemixX, есть ли какие-либо особенности в использовании bitrixdock без WSL? Если да, не могли бы вы дописать их в Readme?

**Comment by webnetkz** [comment]
Основная особенность это работа сети. Изменения не контрибьютелись.

**Comment by paskal** [comment]
Предлагаю дописать в секцию про Windows, мол, "без WSL вам нужно будет произвести следующие изменения в docker-compose.yml: <...>"

**Comment by vmpartner** [comment]
Предлагаю вынести в отдельный файл md, с главной добавить ссылку

сб, 12 окт. 2024 г., 01:07 Dmitry Verkhoturov ***@***.***>:

**Comment by webnetkz** [comment]
Предлагаю не использовать этот контейнер по назначению, только в ознакомительных целях. На стресс тестах focustr падает, при 10% нагрузки. При использовании VM падает на 100%. Выбор очевиден в пользу VM.

**Comment by paskal** [comment]
Вы не могли бы написать поподробнее о том как вы тестировали и какие цифры получили?

Во-первых это интересная информация чтобы добавить в ридми для всех, во-вторых меня интересует методика тестирования поскольку я мог бы провести череду тестов с этими контейнерами и [своим](https://github.com/paskal/bitrix.infra) вариантом, и разобраться, стоит ли вся моя сложность собственной настройки результатов, которые я получу на стресс-тестировании.

В этом проекте я бы провёл отдельные тесты без php-xdebug, поскольку он по понятным причинам здорово ухудшает производительность PHP, однако мне неизвестны другие факторы которые могли бы привести к ухудшению производительности. С другой стороны, я посмотрел, и в версиях php >= 8.0 он в этом проекте не устанавливается, только в <= 7.4, то есть разница в производительности с PHP 8.0 или новее была бы для меня необъяснима.
