### ISSUE TITLE
PHP 8.0.0 or higher is required!

### ISSUE THREAD

**Issue by fzdmd** [bitrixdock/bitrixdock#226]
Битрикс не запустился, как обновить PHP ?

**Comment by Xyslik** [comment]
Похожая ситуация, изменение версии в .env не помогло. Как решили?

**Comment by Elnadrion** [comment]
> Похожая ситуация, изменение версии в .env не помогло. Как решили?

После изменения версии PHP в .env необходимо перебилдить контейнер: `docker compose up -d --build php`

**Comment by Xyslik** [comment]
Премного благодарен
