### ISSUE TITLE
Ошибки при проверке

### ISSUE THREAD

**Issue by gring76** [bitrixdock/bitrixdock#25]
Доброго времени суток.
После переноса сайта в Ваш Docker при проверке появились следующие ошибки

`Выполнение агентов на cron | Ошибка! Не настроен запуск cron_events.php на cron, последний агент отработал больше суток назад.
`
`Отправка почты | Ошибка! Не работает`
`Работа с файлами кеша | Ошибка! Не работает`

Подскажите куда копать? 
З.Ы. Спасибо за Ваши труды. Очень помогло :-)

**Comment by identw** [comment]
А как Вы добавили задачу в cron?
Как я понимаю, судя по docker-compose.yml и docker файлам,  cron нигде не настроен. Для него нужно отдельный контейнер создавать.

**Comment by vmpartner** [comment]
Верно, нужен отдельный контейнер, задача висит, времени пока нет https://github.com/bitrixdock/bitrixdock/issues/22

**Comment by vmpartner** [comment]
Появился рабочий пример https://github.com/bitrixdock/production-single-node
