### ISSUE TITLE
Несколько docker контейнеров с bitrix на одной VM KVM

### ISSUE THREAD

**Issue by rasperepodvipodvert** [bitrixdock/bitrixdock#26]
Можно ли поднять несколько сайтов bitrix на одной VM ?

**Comment by vmpartner** [comment]
Без оркестратора будет сложно. Мы используем rancher в продакшене, Для разработки использую чистые виртуалки virtualbox+alpine

**Comment by vmpartner** [comment]
Поигрался со swarm, оформил в пример https://github.com/vmpartner/docker-swarm-caddy-router

**Comment by rasperepodvipodvert** [comment]
@vmpartner Долго пытаюсь вкурить Ваш пример, так и не понимаю, как его адаптировать под нужды описанные выше.... можете помочь?
