### ISSUE TITLE
Apache?

### ISSUE THREAD

**Issue by alexandermomot** [bitrixdock/bitrixdock#3]
Сторонник nginx, но на хостинге веб-сервер apache. Понимаю что настройки среды боя в .htaccess и локальной разработки могут отличаться, однако же хотелось бы иметь возможность выбора.

**Comment by Lev-Zabudko** [comment]
Тоже столкнулся с тем, что очень нужен такой же compose с apache2

**Comment by vmpartner** [comment]
@pavletto Спасибо за Apache. Сам хотел взяться, но вы меня опередили :)
