### ISSUE TITLE
Как развернуть бэкап на этом контейнере?

### ISSUE THREAD

**Issue by Pum-purum** [bitrixdock/bitrixdock#33]
Сам контейнер запустил, но localhost выдает 443, остальные файлы, куда бы я их не запихивал, пишет No input file specified. Можно пошагово объяснить, куда нажать и что ввести?

**Comment by rasperepodvipodvert** [comment]
@Pum-purum Можете конкретнее описать ваши действия? Только что проверил все по инструкции - работает!

**Comment by rasperepodvipodvert** [comment]
Попробовал командой:
`docker exec mysql /usr/bin/mysql -u bitrix -p123 bitrix < backup.sql`
не получилось :(

**Comment by rasperepodvipodvert** [comment]
Что делал по пунктам:
1. Установил и запустил контейнеры. В результате получил рабочее docker окружение
2. Скопировал готовый файл в папку www/html 
3. Попытался залить базу из архива в mysql ... 
`docker exec mysql /usr/bin/mysql -u bitrix -p123 bitrix < backup.sql`
на этом все закончилось... кто-нибудь знает как дальше?

**Comment by Pum-purum** [comment]
Я знаю. Устанавливаешь OpenServer и работаешь в нем, не зная геморроя. Все эти docker-гуру пишут инструкции для себе подобных, где простому смертному не разобраться ни в жизнь.

**Comment by rasperepodvipodvert** [comment]
Вот так можно залить базу:
`cat /var/www/bitrix/backup.sql | docker exec -i mysql /usr/bin/mysql -u root -p123 bitrix`

**Comment by vmpartner** [comment]
Интересный способ. Спасибо. Добавьте в описание если не трудно.

вт, 3 июл. 2018 г., 15:49 filatovzru <notifications@github.com>:

**Comment by xfg** [comment]
> Сам контейнер запустил, но localhost выдает 443, остальные файлы, куда бы я их не запихивал, пишет No input file specified. Можно пошагово объяснить, куда нажать и что ввести?

Смотри в файле .env переменную окружения `SITE_PATH` по умолчанию там `/var/www/bitrix` укажи абсолютный путь до директории куда кладешь файлы. После этого перезапусти контейнеры и заработает.

**Comment by rasperepodvipodvert** [comment]
Окружение можно запустить уже на рабочем проекте, как правило проекты на bitrix это интернет-магазины и у них куча файлов, которые могут копироваться и час и два и больше, а тут указал папку и на тебе - работай сразу в окружении!

Наверное так :)
