### ISSUE TITLE
Работа с сокетами

### ISSUE THREAD

**Issue by kirillz** [bitrixdock/bitrixdock#34]
Как исправить работу с сокетами?  окружение поднято на локалхосте. /etc/hosts поправил, ошибка не исправлена. Что я делаю не так?
![scr](https://user-images.githubusercontent.com/1161809/39672317-9ef3418e-5130-11e8-88f2-4e090283ee56.png)
в логах битрикс:
```
2018-May-06 13:31:04 Работа с сокетами (check_socket): Fail
Connection to localhost:80	Fail
Socket error [99]: Cannot assign requested address
```
$ cat /etc/hosts
```
127.0.0.1 localhost.localdomain localhost
127.0.1.1 note


```

**Comment by steqtk** [comment]
Я решил проблему так:
1. docker ps
![1](https://user-images.githubusercontent.com/18328271/42127175-89ad7320-7c9c-11e8-9ef5-12148a11e364.png)
2. Копируем CONTAINER ID у bitrixdock_web_server.
3. docker exec -it <тот-самый-id> bash
4. cat /etc/hosts
![2](https://user-images.githubusercontent.com/18328271/42127192-c39a669c-7c9c-11e8-8e13-a60ad03d73a6.png)
5. Копируем самый последний IP в списке.
6. exit
7. Открываем свой /etc/hosts и вписываем этот IP и, например, bitrix.loc
![3](https://user-images.githubusercontent.com/18328271/42127227-254d89be-7c9d-11e8-83fb-0129e88bfc79.png)
profit!
