### ISSUE TITLE
Не стартует mysql на чистом debian 9

### ISSUE THREAD

**Issue by rasperepodvipodvert** [bitrixdock/bitrixdock#35]
`CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                          PORTS                                                  NAMES
8616c65f149d        bitrixdock_web_server   "nginx"                  7 minutes ago       Up 7 minutes                    192.168.10.13:80->80/tcp, 192.168.10.13:443->443/tcp   webserver
96355d7fc82f        bitrixdock_php          "/bin/sh -c /usr/bin…"   7 minutes ago       Up 7 minutes                    192.168.10.13:9000->9000/tcp                           php
53028599f4d2        bitrixdock_mysql        "docker-entrypoint.s…"   7 minutes ago       Restarting (1) 46 seconds ago                                                          mysql
26e2f4a3538e        memcached:1.5-alpine    "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes                    192.168.10.13:11211->11211/tcp                         memcached
`
Как можно проверить/заставить работать mysql?

**Comment by rasperepodvipodvert** [comment]
`mysql         | Initializing database
mysql         | 2018-05-29T21:40:22.357529Z 0 [Warning] option 'binlog_cache_size': unsigned value 0 adjusted to 4096
mysql         | 2018-05-29T21:40:22.357582Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql         | 2018-05-29T21:40:22.357596Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
mysql         | 2018-05-29T21:40:22.358776Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
mysql         | 2018-05-29T21:40:22.358802Z 0 [ERROR] Aborting
`

**Comment by pavletto** [comment]
Проблема состоит в том,  что на хосте уже имеется mysql, который инициализирован.
`[ERROR] --initialize specified but the data directory has files in it. Aborting. mysql`
Дело в том что образ использует в качестве основы официальный образ mysql, который имеет следующую строку в Dockerfile 
`VOLUME /var/lib/mysql`
Можно попробовать решить эту проблему изменив точку монтирования или почистив `/var/lib/mysql`

**Comment by PashtetForever** [comment]
Добрый день! Та же самая проблема(( но при первом запуске выдает ошибку:
`Fatal error: Illegal or unknown default time zone 'Europe/Moscow'`
А если повторить запуск выдает:
`[ERROR] --initialize specified but the data directory has files in it. Aborting.`

Не смотря на то что перед повторным запуском выполнил команды:
`docker-compose down
docker-compose kill`

Так же запускал на чистом Debain 9

Подскажите пожалуйста, почему может возникать такая проблема? Заранее спасибо!

**Comment by vmpartner** [comment]
Закрыто в #36, спасибо @r-novikov-it 
@PashtetForever, проверьте, пжл
