### ISSUE TITLE
Несколько сайтов в одном контейнере

### ISSUE THREAD

**Issue by rasperepodvipodvert** [bitrixdock/bitrixdock#41]
Подскажилте, пожалуйста, как запустить несколько сайтов в одном контейнере?

**Comment by vmpartner** [comment]
Мне кажется вы не правильно поняли идеологию докера. Он сделан чтобы разделять сложные вещи на мелкие и простые, а не наоборот.

**Comment by vmpartner** [comment]
https://github.com/vmpartner/docker-swarm-caddy-router
