### ISSUE TITLE
Не реагирует на изменения в .env файле

### ISSUE THREAD

**Issue by steqtk** [bitrixdock/bitrixdock#45]
Согласно README.md и подсказкам в .env_template меняю PHP_VERSION=56 и WEB_SERVER_TYPE=apache
затем docker-compose up -d
и... php 7.1.8, nginx/1.13.12

Вопрос: что я делаю не так?

**Comment by vmpartner** [comment]
Может забыли сделать cp -f .env_template .env

**Comment by steqtk** [comment]
Копию сделал, не забыл. Всё согласно README.md
Пробовал просто заново клонировать и всё с начала - ничего, не реагирует на изменения в .env

**Comment by vmpartner** [comment]
Видимо что-то у вас в окружении, так не разобраться, пропишите жестко значений переменных в файл docker-compose, они все равно больше для удобства первого запуска, чем для реального проекта.
