### ISSUE TITLE
Сайт работал в однобайтовой кодировке

### ISSUE THREAD

**Issue by steqtk** [bitrixdock/bitrixdock#46]
Известная ошибка - "Сайт работал в однобайтовой кодировке, а конфигурация сервера рассчитана на кодировку UTF-8. Для продолжения установите настройки PHP: mbstring.func_overload=0 или mbstring.internal_encoding=ISO-8859-1.", но решения не нашел. 
Непонятно где указывать эти параметры? Инструкции для .htaccess уже не обрабатываются в новых версия php.

**Comment by vmpartner** [comment]
Сайт сейчас можно легко конвертировать в UTF8, например файлы с помощью программы 
 UTFCast Express https://www.rotatingscrew.com/utfcast-express.aspx, а базу просто снимите дамп и залейте в новую с кодировкой UTF8
