### ISSUE TITLE
Настройки nginx, ошибка 404 при переходе по ЧПУ ссылкам

### ISSUE THREAD

**Issue by fannur** [bitrixdock/bitrixdock#48]
После чистой установке, ошибка при переходе в разделы, например в http://127.0.0.1/catalog/dresses/
```
404 Not Found
nginx
```

Лог nginx:
```
2018/08/16 21:29:26 [error] 6#6: *643 "/var/www/bitrix/catalog/dresses/index.php" is not found (2: No such file or directory), client: 10.100.0.1, server: bitrix, request: "GET /catalog/dresses/ HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/catalog/"
```

пс. Система - macOS

**Comment by vmpartner** [comment]
Не разобрались ещё? urlrewrite корректно настроен?

**Comment by codeguyw** [comment]
такая же проблема: не важно, какой тип сервера выставлен - создается впечатление, что он их не подхватывает и ЧПУ не подхватывает. 

Проект переносился с локальной машины и прекрасно работал со стандартным htaccess и прекрасно отрабатывал urlrewrite. На сервере во внешней части есть лишь nginx в котором был настроен proxy_pass на нужный порт - может в нем надо что-то прописать как-то иначе?


`  server {
	listen 80;
        server_name  mysite.ru www.mysite.ru;
        root /home/folder/web/bitrixdock/www/html;
        index index.php;
	location / {
		root /home/folder/web/bitrixdock/www/html/;
	      	proxy_pass http://localhost:18002;
	      	proxy_set_header Host $host;
	      	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	      	proxy_set_header X-Real-IP $remote_addr;
	}
    }  `

**Comment by vmpartner** [comment]
За ЧПУ отвечает скрипт urlrewrite.php
Вот проброс к нему

```
location / {
        if (-f /var/www/bitrix/index.php) {
             root /var/www/bitrix;
            break;
        }
        if (-f /var/www/bitrix/bitrixsetup.php) {
            root /var/www/bitrix;
            break;
        }
        try_files $uri $uri/ @bitrix;
        root  /var/www/html;
    }

    location @bitrix {
        fastcgi_pass php-upstream;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/bitrix/urlrewrite.php;
    }
```

Смотрите файл https://github.com/bitrixdock/bitrixdock/blob/master/nginx/conf/default.conf

**Comment by codeguyw** [comment]
vmpartner да, в курсе, что мне нужно добраться до urlrewrite - это и не работает (.
Я только что полностью очистил папки apache и nginx от содержимого внутри контейнера и сделал докер-компоуз рестарт - сервер нормально работает БЕЗ конфигов - это вообще нормально?

Я правильно делаю? Ваш проброс сунул в nginx.conf вне контейнера. Но при этом nginx ругался на php-upstream - требовал ip:port вставил ему свой localhost:18002; - сайт перестал работать, выдает 502 ошибку:
2018/08/31 14:02:25 [error] 27332#0: *3 no live upstreams while connecting to upstream, client: 217.28.209.156, server: mysite.ru, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://localhost", host: "mysite.ru", referrer: "http://mysite.ru/"
По-моему я что-то не так понимаю или делаю... (

**Comment by codeguyw** [comment]
Есть у вас какие-то предложения или возможность исправить? Предложенный вами вариант конфигурации nginx - не работает (. И urlrewrite он даже не пытается искать (.

**Comment by vmpartner** [comment]
Попробуйте рабочий пример https://github.com/bitrixdock/production-single-node

**Comment by lokkomokko** [comment]
@vmpartner ну это не ответ, помогите разобраться почему 404я в вашем докере с сервером nginx. В рабочем примере используется php5, что для меня например исключает возможность его использования

**Comment by lokkomokko** [comment]
Так же апач у вас не работает, все очень странно сконфигурированно, приходится вручную править чтобы работало
