### ISSUE TITLE
Не запускается bitrixsetup.php

### ISSUE THREAD

**Issue by doctorx32** [bitrixdock/bitrixdock#5]
Здравствуйте, вроде успешно установил, со стороны клиента могу получить страницу с надписью "BitrixDock Online!", но при обращении http://SERVERIP/bitrixsetup.php получаю 502 Bad Gateway, в логе bitrix-error.log появляется строка с "connect() failed (113: No route to host)". Также пробовал запустить скрипт внутри сервера с помощью `php ./bitrixsetup.php`, просто выводит внутренность файла, как будто я выполнил cat ./bitrixsetup.php. Подскажите пожалуйста, как правильно запускать этот скрипт?

Пути не менял, меня устраивают. Ubuntu 16.04.3

**Comment by pavletto** [comment]
Что используете в качестве сервера?

**Comment by vmpartner** [comment]
Думаю у вас link c nginx на php не прописался, попробуйте пропинговать.

13 окт. 2017 г. 21:02 пользователь "doctorx32" <notifications@github.com>
написал:

**Comment by doctorx32** [comment]
**pavletto**, nginx. **vmpartner**, догадываюсь, что Вы не про команду ping, можете пожалуйста поподробней?))

**Comment by vmpartner** [comment]
Я как раз про ping. Зайдите в контейнер с nginx и введите ping php. (Нужно будет поставить пакет ping: apt update && apt install iputils-ping)

**Comment by doctorx32** [comment]
`dmitry@bitrix:/var/www/bitrixdock/php$ sudo docker exec -it 911472c3ca4f bash
root@911472c3ca4f:/# apt update && apt install iputils-ping
Get:1 http://security.debian.org stretch/updates InRelease [62.9 kB]
Get:2 http://nginx.org/packages/mainline/debian stretch InRelease [2857 B]
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://security.debian.org stretch/updates/main amd64 Packages [222 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2479 B]
Get:8 http://nginx.org/packages/mainline/debian stretch/nginx amd64 Packages [18.0 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [5841 B]
Get:10 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9500 kB]
Fetched 10.0 MB in 2s (4741 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libcap2 libcap2-bin libidn11 libnettle6 libpam-cap
The following NEW packages will be installed:
  iputils-ping libcap2 libcap2-bin libidn11 libnettle6 libpam-cap
0 upgraded, 6 newly installed, 0 to remove and 5 not upgraded.
Need to get 421 kB of archives.
After this operation, 970 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libcap2 amd64 1:2.25-1 [16.8 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libidn11 amd64 1.33-1 [115 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libnettle6 amd64 3.3-1+b2 [192 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 iputils-ping amd64 3:20161105-1 [57.5 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libcap2-bin amd64 1:2.25-1 [26.5 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libpam-cap amd64 1:2.25-1 [13.5 kB]
Fetched 421 kB in 0s (3449 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libcap2:amd64.
(Reading database ... 7030 files and directories currently installed.)
Preparing to unpack .../0-libcap2_1%3a2.25-1_amd64.deb ...
Unpacking libcap2:amd64 (1:2.25-1) ...
Selecting previously unselected package libidn11:amd64.
Preparing to unpack .../1-libidn11_1.33-1_amd64.deb ...
Unpacking libidn11:amd64 (1.33-1) ...
Selecting previously unselected package libnettle6:amd64.
Preparing to unpack .../2-libnettle6_3.3-1+b2_amd64.deb ...
Unpacking libnettle6:amd64 (3.3-1+b2) ...
Selecting previously unselected package iputils-ping.
Preparing to unpack .../3-iputils-ping_3%3a20161105-1_amd64.deb ...
Unpacking iputils-ping (3:20161105-1) ...
Selecting previously unselected package libcap2-bin.
Preparing to unpack .../4-libcap2-bin_1%3a2.25-1_amd64.deb ...
Unpacking libcap2-bin (1:2.25-1) ...
Selecting previously unselected package libpam-cap:amd64.
Preparing to unpack .../5-libpam-cap_1%3a2.25-1_amd64.deb ...
Unpacking libpam-cap:amd64 (1:2.25-1) ...
Setting up libnettle6:amd64 (3.3-1+b2) ...
Setting up libcap2:amd64 (1:2.25-1) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Setting up libidn11:amd64 (1.33-1) ...
Setting up iputils-ping (3:20161105-1) ...
Setting up libpam-cap:amd64 (1:2.25-1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libcap2-bin (1:2.25-1) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
root@911472c3ca4f:/# ping php
ping: php: Name or service not known
root@911472c3ca4f:/#`

**Comment by vmpartner** [comment]
Похоже я угадал. Вы link в nginx в docker compose не меняли? Попробуйте
снова с исходными файлами предварительно удалив все контейнеры.

15 окт. 2017 г. 13:58 пользователь "doctorx32" <notifications@github.com>
написал:

**Comment by pavletto** [comment]
Выполните следующее в директории проекта:
`
sudo docker-compose kill 
sudo docker-compose rm
git checkout docker-compose.yml
sudo docker-compose up
`

**Comment by doctorx32** [comment]
https://pastebin.com/yFkzAUii

Все равно 502 Bad Gateway по /bitrixsetup.php, а / по прежнему успешно отображает главную страницу, кстати такая же ошибка и по заведомо неправильному url (например, /bitrixsetup2.php). php exited with code 0 появляются сразу после `sudo docker-compose up`, а также после каждого обращения с браузера клиента. Копии файлов bitrixsetup.php лежат в /var/www/bitrix, /var/www/bitrixdock и в /var/www/bitrixdock/nginx/www. 
Большая ли вероятность проблемы из-за того, что bitrixdock склонирован в папку /var/www от root, а также директории bitrixdock и bitrix доступны только ему?

**Comment by vmpartner** [comment]
Если у вас нет других контейнеров и важных образов и волиумов, то попробуйте снести всё командой:
```
docker stop $(docker ps -q) && docker rm $(docker ps -a -q) && docker rmi $(docker image ls -q) && docker volume rm $(docker volume ls -q)
```
Далее с нуля по инструкции попробуйте заново. Уверен, что у вас проблема в линках c nginx до php.

**Comment by doctorx32** [comment]
все выполненные команды для переустановки: https://pastebin.com/gWNtzwDB

волумов не было, поэтому скорей всего не проблема что соответствующая команда не выполнилась на 84 строчке.

По прежнему такая же проблема, там же в логе выполнял `netstat -plnt`, видно, что нет процесса с портом 9000

**Comment by vmpartner** [comment]
Не удаётся повторить. Ошибка больше ни у кого не проявляется. У вас какая то локальная ошибка с php.
