### ISSUE TITLE
Куча ошибок при проверке

### ISSUE THREAD

**Issue by stanislavsay** [bitrixdock/bitrixdock#50]
На свеже установленном докере куча ошибок при тестировании. В частности ошибки сокетов и, что важно, Push and Pull и все что с ним связано:
![2018-08-17 16 01 00](https://user-images.githubusercontent.com/11972804/44267552-5fdcb180-a237-11e8-8905-2d8cd493d220.png)
Как настраивать все это хозяйство не понятно)))

**Comment by RushCode** [comment]
Нужно поставить моудль nginx-push-stream или поднять на nodejs pub/sub сервер.

**Comment by rasperepodvipodvert** [comment]
Ошибка с сокетами возникает если доменное имя такое не зарегистрировано, соотвественно битрик нужно разворачивать либо сразу на нормальный домен либо в место домена использовать IP. Делаю так и этой ошибки нет!

**Comment by alapaev** [comment]
Развернул контейнеры на локалке, захожу по 127.0.0.1
Все равно выдается ошибка работы с сокетами. Кто-то смог решить проблему?

**Comment by vmpartner** [comment]
Попробуйте данный пример https://github.com/bitrixdock/production-single-node
Там с сокетами всё ок.
