### ISSUE TITLE
не работает адание в интерфейсе дургого ip - подняие контейнера валится с ошибкой

### ISSUE THREAD

**Issue by Vampiref92** [bitrixdock/bitrixdock#52]
не работает адание в интерфейсе дургого ip - подняие контейнера валится с ошибкой
![2018-09-09 11-39-04](https://user-images.githubusercontent.com/3988646/45262719-17bf4200-b425-11e8-9e18-398aa6b6f537.png)

**Comment by vmpartner** [comment]
@identw Не подскажешь?

**Comment by identw** [comment]
@Vampiref92 
10.100.20.10 - этот ip принадлежит Вашему интерфейсу?
У Вас судя по скрину Ubuntu, дайте вывод `ip a`

**Comment by Vampiref92** [comment]
4: br-08f7bea2cbaa: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default    link/ether 02:42:2f:93:68:44 brd ff:ff:ff:ff:ff:ff    inet 10.100.20.1/24 brd 10.100.20.255 scope global br-08f7bea2cbaa       valid_lft forever preferred_lft forever    inet6 fe80::42:2fff:fe93:6844/64 scope link       valid_lft forever preferred_lft forever Вот вывода вот полный вывод user@user-GP62M-7RDX:~$ ip a1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00    inet 127.0.0.1/8 scope host lo       valid_lft forever preferred_lft forever    inet6 ::1/128 scope host       valid_lft forever preferred_lft forever2: enp3s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000    link/ether 30:9c:23:15:9d:8c brd ff:ff:ff:ff:ff:ff3: wlp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000    link/ether f8:94:c2:da:7b:86 brd ff:ff:ff:ff:ff:ff    inet 192.168.1.87/24 brd 192.168.1.255 scope global dynamic noprefixroute wlp2s0       valid_lft 86196sec preferred_lft 86196sec    inet6 fe80::1171:a478:d7cc:65c1/64 scope link noprefixroute       valid_lft forever preferred_lft forever4: br-08f7bea2cbaa: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default    link/ether 02:42:2f:93:68:44 brd ff:ff:ff:ff:ff:ff    inet 10.100.20.1/24 brd 10.100.20.255 scope global br-08f7bea2cbaa       valid_lft forever preferred_lft forever    inet6 fe80::42:2fff:fe93:6844/64 scope link       valid_lft forever preferred_lft forever5: br-69491f386152: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default    link/ether 02:42:07:80:5b:9d brd ff:ff:ff:ff:ff:ff    inet 172.20.0.1/16 brd 172.20.255.255 scope global br-69491f386152       valid_lft forever preferred_lft forever6: br-6a74a34f4c2e: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default    link/ether 02:42:6d:d8:4c:61 brd ff:ff:ff:ff:ff:ff    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-6a74a34f4c2e       valid_lft forever preferred_lft forever7: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default    link/ether 02:42:a1:eb:7b:32 brd ff:ff:ff:ff:ff:ff    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0       valid_lft forever preferred_lft forever9: vethd4ad98c@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-08f7bea2cbaa state UP group default    link/ether 92:e6:08:77:a4:dd brd ff:ff:ff:ff:ff:ff link-netnsid 1    inet6 fe80::90e6:8ff:fe77:a4dd/64 scope link       valid_lft forever preferred_lft forever11: vethacc9117@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-08f7bea2cbaa state UP group default    link/ether 52:b4:b5:49:e1:0b brd ff:ff:ff:ff:ff:ff link-netnsid 0    inet6 fe80::50b4:b5ff:fe49:e10b/64 scope link       valid_lft forever preferred_lft forever13: veth2f0f3f1@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-08f7bea2cbaa state UP group default    link/ether 9a:5b:ed:84:b5:44 brd ff:ff:ff:ff:ff:ff link-netnsid 3    inet6 fe80::985b:edff:fe84:b544/64 scope link       valid_lft forever preferred_lft forever15: veth70f0f90@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-08f7bea2cbaa state UP group default    link/ether ba:fd:30:a0:18:17 brd ff:ff:ff:ff:ff:ff link-netnsid 2    inet6 fe80::b8fd:30ff:fea0:1817/64 scope link       valid_lft forever preferred_lft forever   -- С уважением, Фролов Сергей.15.09.2018, 19:13, "identw" <notifications@github.com>:@Vampiref92
10.100.20.10 - этот ip принадлежит Вашему интерфейсу?
У Вас судя по скрину Ubuntu, дайте вывод ip a

**Comment by identw** [comment]
@Vampiref92 
Воспользуйтесь тегами оформления, или pasterbin сервисами. Нет желания разбираться в не отформатированном выводе.

**Comment by Vampiref92** [comment]
https://pastebin.com/QmDtxMNcтут вывод тоже не сильно отличается - ибо bash не всемогущ-- С уважением, Фролов Сергей.15.09.2018, 22:36, "identw" <notifications@github.com>:@Vampiref92
Воспользуйтесь тегами оформления, или pasterbin сервисами. Нет желания разбираться в не отформатированном выводе.

**Comment by identw** [comment]
Достаточно добавить теги(исполняемые ковычки) обрамив ими Ваш вывод, и уже будет читабально. Ну или в pasterbin сервисе. Теперь видно
Выставляя для переменной `INTERFACE` ip адрес `10.100.20.10`, чего Вы хотели добиться?
`INTERFACE` - необходим, для того  чтобы прокидывать порт из контейнера на хост. То есть этот IP адрес должен быть на хостовой машине. А у Вас ни на каком интерфейсе данного ip адреса нет.

**Comment by Vampiref92** [comment]
все просто хочется иметь возможность разным контейнерам указывать разные адреса для запуска, + к ним подвязать уже имена. не хочу чтобы все вращалоь на локальном, к тмоу же так нельзя будет быстро запустить контейнер из-за конфликтов, надо будет стопать старый. С интерфейсами в докере пока не разобрался сам. думал тут именно так сделано - вроде как это реально через задание моста. Если так уже делали, хотелось бы знать что именно нужно для этого)В любом случае спасибо)-- С уважением, Фролов Сергей.15.09.2018, 22:59, "identw" <notifications@github.com>:Достаточно добавить теги(исполняемые ковычки) обрамив ими Ваш вывод, и уже будет читабально. Ну или в pasterbin сервисе. Теперь видно
Выставляя для переменной INTERFACE ip адрес 10.100.20.10, чего Вы хотели добиться?
INTERFACE - необходим, для того  чтобы прокидывать порт из контейнера на хост. То есть этот IP адрес должен быть на хостовой машине. А у Вас ни на каком интерфейсе данного ip адреса нет.
