### ISSUE TITLE
ошибка при запуске на MacOs

### ISSUE THREAD

**Issue by barysh** [bitrixdock/bitrixdock#56]
ERROR: for 5ac1ebd832db_source  Cannot start service source: b'Mounts denied: \r\nThe path /var/www/bitrix\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

**Comment by mikhailsidorov** [comment]
> ERROR: for 5ac1ebd832db_source Cannot start service source: b'Mounts denied: \r\nThe path /var/www/bitrix\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

Add necessary directory to File Sharing in your Docker preferences.
![image](https://user-images.githubusercontent.com/7780462/48570278-0c9cfc80-e915-11e8-88ae-f495be86c28e.png)

**Comment by vUdav** [comment]
Измени в .env конфиг на `SITE_PATH=./www`
