### ISSUE TITLE
Ошибок нет...

### ISSUE THREAD

**Issue by FaritSlv** [bitrixdock/bitrixdock#6]
Здравствуйте. 
У Вас в описании написано: "Если вы работаете в Windows, то требуется установить виртуальную машину. Желательно использовать Virtualbox, сделать сеть "Сетевой мост", поставить Ubuntu Server 16.04. " Скажите, пожалуйста: "А зачем это делать? Это решает какие-то определенные задачи?"

**Comment by vmpartner** [comment]
Как правило веб-разработчики сидят на Linux, так как это удобнее для разработки и настройки окружения. Любители Windows и Mac обходят неудобства виртуалками. Я сам сижу на Windows хотя знаю Linux хорошо и работаю с в ней каждый день. Проще всего в поддержке Ubuntu, так как очень большое сообщество. Virtualbox одна из стабильных и популярных виртуалок. Из этих пунктов и складывается мой совет :)

**Comment by zamkevich** [comment]
Вопрос наверное был в том, зачем в принципе юзать VB. Так вот, от нужен чтобы разрабатывать проект локально не загружая файлы на сервер. VB позволяет быстро поднять нужное окружение без танцев с бубном. Особенно это полезно для работы на проектах в продакшне. Сделал себе локальную копию и пилишь потихоньку не трогая боевой сервер. 

У Битрикса есть готовые виртуальные машины.  Но с ними есть одна загвоздка: файлы всё ещё как бы находятся «на сервере» и к ним нет прямого доступа. 

С Докером нет такой проблемы. У вас по умолчанию прямой доступ к файлам из вашей системы, так как это обычные папки.
