### ISSUE TITLE
Почта. Как настроить почту ? Не работает.

### ISSUE THREAD

**Issue by lokkomokko** [bitrixdock/bitrixdock#61]

**Comment by dzhaparoff** [comment]
Не помогает, почта не работает

**Comment by lokkomokko** [comment]
У ребят почти ничего не работает, все со скрипом, и своими дописываниями. Как вариант можно опять же самому ручками в контейнере с php установить sendmail софт, так как изначально его там нет, видимо проблема из за этого, но вот опять же зачем тогда использовать такой продукт, где приходится все дописывать самому. 
Я лично, плюнул на это мракобесие, поставил докер с CentOs, и автодеполоем скрипта парней из битрикса (https://www.1c-bitrix.ru/products/env/), установил необходимое окружение. Куда меньше мороки чем вот со всем этим.

**Comment by dzhaparoff** [comment]
Поставил другой образ с php-fpm + msmtp, как итог - все работает.

**Comment by rasperepodvipodvert** [comment]
я тестировал nginx-phpfpm у меня работает очень хорошо!

**Comment by vmpartner** [comment]
Посмотрите как сделано в этом проекте https://github.com/bitrixdock/production-single-node
Там используется msmtp, просто и надежно.
