### ISSUE TITLE
.env в .gitignore (force)

### ISSUE THREAD

**Issue by spiritabsolute** [bitrixdock/bitrixdock#69]
If you have already added the files to be tracked, you need to remove them from tracking:

```
git rm .env --cached
git commit -m "Stopped tracking .env"
```

Now you should be able to clone your branch without those files being tracked.

> Note: Keep in mind that the contents of those files are in your history, and if they did contain sensitive data, then you need to completely remove that from history before putting it out there.

**Comment by vmpartner** [comment]
Да мы здесь на русском общаемся, иностранных гостей не предвидеться ))
Удалить то можно, но зачем, людям так удобней.
