### ISSUE TITLE
"Архив с полной сборкой решения (.last_version.zip или .last_version.tar.gz или .last_version.tgz) Загружайте сборку в кодировке win-1251."

### ISSUE THREAD

**Issue by 6umpukc-uHKBu3umop** [bitrixdock/bitrixdock#76]
для разработки bitrix решений - есть требование использовать кодировку win-1251

(в заголовке цитата из личного кабинета для загрузки решений)

можете сделать возможность выбора кодировки для сайта?

например в файле .env чтоб задавать кодировку 

`BITRIX_ENCODING=windows-1251 # или UTF-8`

сейчас можно только в UTF-8 создавать

**Comment by Medic84** [comment]
Проще (и имхо правильнее т.к. весь мир уже на UTF8) разрабатывать на UTF8 и написать маленький скриптик который через **iconv** конвертирует Вам в нужную кодировку.

**Comment by 6umpukc-uHKBu3umop** [comment]
да уже неактуально - я пользуюсь уже больше 2 лет lxd со стандартным окружением bitrix-env

там кодировка windows-1251 поддерживается без каких либо проблем
