### ISSUE TITLE
docker запускает все контейнеры - но есть проблемы с правами при запуске bitrixsetup.php

### ISSUE THREAD

**Issue by rivetweb** [bitrixdock/bitrixdock#78]
Warning:  fopen(/var/www/bitrix/start_encode.tar.gz.log): failed to open stream:  Permission denied in /var/www/bitrix/bitrixsetup.php on line 898
--

1 | 0.0001 | 362984 | {main}(  ) | .../bitrixsetup.php:0
2 | 0.0003 | 373960 | LoadFile(  ) | .../bitrixsetup.php:612
3 | 0.3739 | 377656 | fopen (  ) | .../bitrixsetup.php:898

**Comment by n37w1z** [comment]
попробуйте, тупо chmod 777 /var/www/bitrix/bitrixsetup.php
если работает, то потберите более безопасные для вашего случая настройки.

**Comment by tomasevich** [comment]
Решение https://github.com/bitrixdock/bitrixdock/issues/92
