### ISSUE TITLE
ERROR: Unable to open primary script: /var/www/bitrix/bitrix/urlrewrite.php (No such file or directory)

### ISSUE THREAD

**Issue by n37w1z** [bitrixdock/bitrixdock#80]
ERROR: Unable to open primary script: /var/www/bitrix/bitrix/urlrewrite.php (No such file or directory)

**Comment by EvgeniyTaburyanskiy** [comment]
А как решили-то ?
Склонировал проект  , 
настройки поправил в .env ,
стартанул докер,
в логах ошибок nginx валит кучи ошибок /var/www/bitrix/bitrix/urlrewrite.php

**Comment by vmpartner** [comment]
Привет. urlrewrite должен быть в корне /var/www/bitrix/urlrewrite.php

**Comment by vmpartner** [comment]
Видимо в этом файле ошибка https://github.com/bitrixdock/bitrixdock/blob/master/nginx/conf/default.conf

**Comment by vmpartner** [comment]
Поправил, сможете протестировать?

**Comment by vmpartner** [comment]
Хотя нет, посмотрел в коде, вроде всё верно, вернул как было )
