### ISSUE TITLE
phpmyadmin

### ISSUE THREAD

**Issue by SegaWeb** [bitrixdock/bitrixdock#82]
Огромное спасибо за проделанную работу!

Все работает. Но вот вопрос:
Возможно ли работать с базой из phpmyadmin  в этой системе? Что для этого нужно сделать?  Может мануалы какие-то есть? В docker не силен (

**Comment by akopkesheshyan** [comment]
Вы можете подключить phpMyAdmin отдельным контейнером используя docker compose.

По ссылке найдете [пример](https://github.com/akopkesheshyan/bitrix24-docker/blob/master/docs/02-phpmyadmin-setup.md) на базе моей сборки Битрикс для Docker.

**Comment by rasperepodvipodvert** [comment]
close
