### ISSUE TITLE
Отправка сообщений

### ISSUE THREAD

**Issue by TheDragovich** [bitrixdock/bitrixdock#83]
Возможно ли как-либо настроить отправку писем в данном докере?

**Comment by vmpartner** [comment]
Данный проект учебный. Реальный пример с отправкой писем https://github.com/bitrixdock/production-single-node

**Comment by vmpartner** [comment]
Ошибся, там нет. Постараюсь добавить.

**Comment by vmpartner** [comment]
https://github.com/bitrixdock/bitrixdock-production
