### ISSUE TITLE
Медленно…

### ISSUE THREAD

**Issue by zamkevich** [bitrixdock/bitrixdock#86]
Поставил на каталину, развернул боевой сайт из бэкапа и — чёт очень долго сервер отвечает… Буквально по 30 сек на каждый запрос, эт ппц. Всё оставил по дефолту, куда копать, в чём может быть проблема?

**Comment by vmpartner** [comment]
Может нет подключения к мемкешу?

пн, 23 дек. 2019 г., 12:29 Misha Zamkevich <notifications@github.com>:

**Comment by zamkevich** [comment]
Да вроде всё ок, или как ещё проверить? 

![image](https://user-images.githubusercontent.com/13717428/71386024-a4037180-2636-11ea-9ce0-cd43da8afa58.png)

**Comment by PetruhaXI** [comment]
Тоже очень медленно на mac. Некоторые страницы сайта загружаются по нескольку минут. При попытке сбросить кэш страницы — просто через несколько минут 

Видимо, это на нагруженных сайтах с большим количеством запросов такое происходит. Но как-то через чур. На виртуальном сервере (боевом) при этом работает нормально.

**Comment by PetruhaXI** [comment]
Помогает вот эта штука: http://docker-sync.io/

**Comment by aspisklov** [comment]
Проблема в файловой системе Мака - https://docs.docker.com/docker-for-mac/osxfs-caching/
Пробовал ставить BitrixDock на Linux виртуалку на Маке, все летает.

**Comment by zamkevich** [comment]
@aspisklov я использую докер только для разработки. Развёртываю / деплою без докера. Так как у всех клиентов обычные хостинги. 

Поэтому запуск на виртуалке убивает весь смысл использовать докер. С тем же успехом я могу просто юзать VM от команды Битрикса.
