### ISSUE TITLE
Использование вместе с битрикс-окружением

### ISSUE THREAD

**Issue by arapeckij** [bitrixdock/bitrixdock#88]
Понадобилось на сервере с битрикс окружением запустить старый сайт на битриксе под php 5, но на сервере используется php7. Думал при помощи этого решения запустить докер в котором будет php5 и потом проксировать запросы в docker.
Итого для web_server указал порты - '${INTERFACE}:9080:80'. Но загвоздка вышла с БД так как на сервере 3306 порт занят. Видимо делаю что-то не так, но как ни пробую настроить получаю ошибки типа
Mysql connect error [localhost:3406, localhost:3406]: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) (400)
или
ysql connect error [mysql:3406, msql:3406]: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) (400)
Как правильно сделать?

**Comment by vmpartner** [comment]
Привет, возьми новую чистую виртуалку на ubuntu 18.04, поставь docker, запусти проект https://github.com/bitrixdock/production-single-node, потом залей свой код и базу

**Comment by arapeckij** [comment]
Так а смысл ставить виртуалку, а внутрь еще и docker? Я не хотел заморачиваться с отдельной установкой php5. Как вариант меня устроит пробросить запрос из контейнера в текущую БД

**Comment by arapeckij** [comment]
Ввело в заблуждение и запутало то что написано использовать для подключения к mysql нужно указывать "mysql" и то что стандартные порты заняты. По факту же надо указывать "db", потому что сейчас имя сервиса db.
Теперь ошибка вот такая Mysql connect error [db, 10.100.0.2]: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory (400)
Попробовал изменить версию mysql на 5.7 и получил:
Mysql connect error [db, db]: Unknown MySQL server host 'db' (2) (400)

**Comment by DarkRiDDeR** [comment]
Имя сервиса сменилось, надо поменять в документации. Для MySQL 8 попробуй добавить команду
command: --default-authentication-plugin=mysql_native_password
версия аутентификации по умолчанию сменилась в новой версии

**Comment by arapeckij** [comment]
Сделал так:
command: mysqld --sql-mode="" --default-authentication-plugin=mysql_native_password
Но результат прежний.

**Comment by arapeckij** [comment]
Переключил на mysql 5.7 поменял 
- db:/var/lib/mysql
на
- ./db:/var/lib/mysql
После чего заработало. Всем спасибо!
