### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by xmount** [bitrixdock/bitrixdock#9]
Здравствуйте,
Попробовал запустить Вашу разработку под windows10, web-сервис работает, а mysql постоянно перезагружается,
ps -a показывает:
f09ccea89783        bitrixdock_mysql       "docker-entrypoint..."   19 seconds ago      Restarting (1) 8 seconds ago                                              mysql
Пробовал менять O_DIRECT на O_DSYNC, но не помогло. В каталоге logs/mysql пусто, а также пусто в data/mysql/ в файле ibdata1
Не подскажете, как узнать причину рестарта и запустить mysql?
И второй вопрос: как бы сделать чтобы для подключения к mysql можно было бы указывать localhost?

**Comment by mikhailsidorov** [comment]
Посмотрите какие ошибки выводятся в консоль. Сложно что-то сказать по вашему описанию.

**Comment by xmount** [comment]
mysql        | Initializing database
mysql        | 2017-11-07T19:30:03.773093Z 0 [Warning] option 'binlog_cache_size': unsigned value 0 adjusted to 4096
mysql        | 2017-11-07T19:30:03.773283Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql        | 2017-11-07T19:30:03.773318Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
mysql        | 2017-11-07T19:30:03.783908Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
mysql        | 2017-11-07T19:30:03.784384Z 0 [ERROR] Aborting
mysql        |
mysql        | Initializing database
и так по кругу

**Comment by mikhailsidorov** [comment]
Удалите каталог data и посмотрите еще раз, что выводится в консоль.

**Comment by xmount** [comment]
mysql        | 2017-11-07T19:37:19.475810Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
mysql        | 2017-11-07T19:37:19.823190Z 0 [Warning] InnoDB: Retry attempts for writing partial data failed.
mysql        | 2017-11-07T19:37:19.829389Z 0 [ERROR] InnoDB: Write to file ./ibdata1failed at offset 0, 1048576 bytes should have been written, only 0 were written. Operating system error number 22. Check that your OS and file system support files of this size. Check also that the disk is not full or a disk quota exceeded.
mysql        | 2017-11-07T19:37:19.829724Z 0 [ERROR] InnoDB: Error number 22 means 'Invalid argument'
mysql        | 2017-11-07T19:37:19.829952Z 0 [ERROR] InnoDB: Could not set the file size of './ibdata1'. Probably out of disk space
mysql        | 2017-11-07T19:37:19.830004Z 0 [ERROR] InnoDB: InnoDB Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
mysql        | 2017-11-07T19:37:20.433616Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
mysql        | 2017-11-07T19:37:20.433679Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mysql        | 2017-11-07T19:37:20.433704Z 0 [ERROR] Failed to initialize plugins.
mysql        | 2017-11-07T19:37:20.433714Z 0 [ERROR] Aborting
mysql        |
mysql        | Initializing database
и далее опять по кругу, каталог создался

**Comment by xmount** [comment]
спасибо, вроде бы заработало!
а попутно не подскажете, как правильно прописать volumes если у меня сайт на диске c:/ в каталоге c:/www/bitrix вместо /var/www/bitrix:/var/www/bitrix ?

**Comment by mikhailsidorov** [comment]
Измените левую часть (до двоеточия) на нужный путь.

**Comment by xmount** [comment]
Вот как раз и вопрос, как правильно этот путь прописать? пробовал и c:/www/bitrix и /c/www/bitrix - все время выдается 404-я ошибка

**Comment by pavletto** [comment]
Попробуйте /mnt/c/www/bitrix. Я для удобства размещаю файлы сайта в корне compose проекта и указываю в volume относительный путь.

**Comment by xmount** [comment]
Здравствуйте!
Спасибо, с этим разобрался, но в macOS возникла небольшая проблема:
у меня часть сайта в одном каталоге, а каталоги bitrix, local и upload находятся уровнем выше и основной каталог сделаны симлинки.
Сделал на своем компьютере симлинки, пробовал и относительные пути указывать, и абсолютные, в консоли они замечательно работают, но в докере их не видно.
Зашел в контейнер nginx-a (командой docker exec -it <id> /bin/bash), перешел в каталог /var/www/bitrix/, в нем каталог к которому сделал симлинк видно, показывает что есть симлинк на другой каталог, но ls -la показывает что это как будто файл и содержимое не показывает, из-за этого сайт не работает.
Не сталкивались ли Вы с такой проблемой или может быть знаете как побороть?

**Comment by vmpartner** [comment]
Симлинки с докером не дружат. Вам нужно монтировать все нужные директории отдельно и симлинки делать внутри контейнера.

**Comment by billo32** [comment]
Проблема актуальна. Mysql перезагружается (Ubuntu 16.04). Менял O_DIRECT на O_DSYNC, без результата. Удалял data и делал docker-compose build и docker-compose up соответственно. без результата.

========

mysql         | 2018-03-29T18:36:56.880863Z 0 [Warning] option 'binlog_cache_size': unsigned value 0 adjusted to 4096
mysql         | 2018-03-29T18:36:56.880928Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql         | 2018-03-29T18:36:56.880940Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
mysql         | 2018-03-29T18:36:57.323585Z 0 [Warning] InnoDB: New log files created, LSN=45790
mysql         | 2018-03-29T18:36:57.409878Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
mysql         | 2018-03-29T18:36:57.477927Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 29321738-3380-11e8-9004-02420a640002.
mysql         | 2018-03-29T18:36:57.480386Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
mysql         | 2018-03-29T18:36:57.480583Z 0 [ERROR] Fatal error: Illegal or unknown default time zone 'Europe/Moscow'
mysql         | 2018-03-29T18:36:57.480594Z 0 [ERROR] Aborting
