### ISSUE TITLE
Ошибка старта сервиса БД

### ISSUE THREAD

**Issue by murzix** [bitrixdock/bitrixdock#90]
не удаётся запустить под Windows 10

> C:\web\work\bitrixdock>docker-compose up -d
Starting source ... done                                                                                             Recreating memcached ...
Recreating db        ... error
ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/db9bd030aa5a9fcf7fa04be01f0581e591504c6592ba8c99c725b03fa9995667/merged\\\" at \\\"/var/lib/docker/overlay2/db9bd030aa5a9fcf7fa04be01f0581e591504c6592ba8c99c725b03fa9995667/merged/usr/share/zoneinfo/UCT\\\Recreating memcached ... done                                                                                        if the specified host path exists and is the expected type

>ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/db9bd030aa5a9fcf7fa04be01f0581e591504c6592ba8c99c725b03fa9995667/merged\\\" at \\\"/var/lib/docker/overlay2/db9bd030aa5a9fcf7fa04be01f0581e591504c6592ba8c99c725b03fa9995667/merged/usr/share/zoneinfo/UCT\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by Slach** [comment]
у вас windows 10 home?
как ставили docker ? через docker-toolbox / docker-machine + virtualbox?
если да, тогда ошибка связана с тем что в docker-compose относительные пути прописаны
они неправильно монтируются внутри virtualbox
мне помог вот этот проект
https://github.com/vweevers/node-docker-share

если у вас win10 pro
то тогда проблема может быть таже самая, а решение должно быть другим

**Comment by murzix** [comment]
> если у вас win10 pro
то тогда проблема может быть таже самая, а решение должно быть другим

Речь о Pro версии. На home докер сейчас не ставится.

**Comment by Slach** [comment]
так похоже дело в том что есть несуществующий volume в docker-compose line 76

https://github.com/bitrixdock/bitrixdock/blame/master/docker-compose.yml#L76
 - /etc/localtime:/etc/localtime/:ro
зачем нужная такая синхронизация, не очень понятно
как временное решение
попробуйте взять откуда нибудь с Linux эту папку /
и положить в корне диска где у вас docker-compose.yaml

вообще надо разбираться как устроена HYPER-V машинка на которой докер под win10pro работает

**Comment by murzix** [comment]
>   попробуйте взять откуда нибудь с Linux эту папку /etc/localtime
>   и положить в корне диска где у вас `docker-compose.yaml`
> 
> вообще надо разбираться как устроена HYPER-V машинка на которой докер под win10pro работает

Ок, сейчас попробую

**Comment by murzix** [comment]
Завелось. Можно дополнить документацию 

> ⚠ Если у вас мак, удалите строчку /etc/localtime:/etc/localtime/:ro из docker-compose

Для Windows тоже работает
