### ISSUE TITLE
Автоматическая установка

### ISSUE THREAD

**Issue by abicorios** [bitrixdock/bitrixdock#91]
Похоже автоматическая установка имеет не достаточно дружелюбный интерфейс.
Выполняем на Ubuntu 18 команду:

```
curl -fsSL https://raw.githubusercontent.com/bitrixdock/bitrixdock/master/install.sh -o install.sh | chmod +x install.sh | sh install.sh
```

Видим приветствие:

```
chmod: cannot access 'install.sh': No such file or directory
sh: 0: Can't open install.sh
```

Уточните пожалуйста системные требования. Что нужно сделать с системой чтобы автоматическая установка сработала?

**Comment by lain0** [comment]
```curl -fsSL https://raw.githubusercontent.com/bitrixdock/bitrixdock/master/install.sh -o install.sh && chmod +x install.sh && sh install.sh```

**Comment by abicorios** [comment]
> `curl -fsSL https://raw.githubusercontent.com/bitrixdock/bitrixdock/master/install.sh -o install.sh && chmod +x install.sh && sh install.sh`

Такой способ установки не описан в readme проекта.

**Comment by abicorios** [comment]
Вижу закрыт issue. У меня всё ещё не работает автоматическая установка. Хоть упомянутый выше способ и добавлен в readme, ошибка просто поменялась на другую. Теперь выглядит так:
```
Check requirments
install.sh: line 8: [: hash: unary operator expected
install.sh: line 9: [: hash: unary operator expected
install.sh: line 10: [: hash: unary operator expected
Create folder struct
--2020-11-27 09:26:31--  http://www.1c-bitrix.ru/download/scripts/bitrixsetup.php
Resolving www.1c-bitrix.ru (www.1c-bitrix.ru)... 99.81.101.35
Connecting to www.1c-bitrix.ru (www.1c-bitrix.ru)|99.81.101.35|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.1c-bitrix.ru/download/files/scripts/bitrixsetup.php [following]
--2020-11-27 09:26:31--  http://www.1c-bitrix.ru/download/files/scripts/bitrixsetup.php
Reusing existing connection to www.1c-bitrix.ru:80.
HTTP request sent, awaiting response... 200 OK
Length: 129820 (127K) [application/octet-stream]
Saving to: ‘bitrixsetup.php’

100%[=================================================================================================================================================================>] 129,820      688KB/s   in 0.2s   

2020-11-27 09:26:31 (688 KB/s) - ‘bitrixsetup.php’ saved [129820/129820]

install.sh: line 17: git: command not found
Config
cp: cannot stat ‘.env_template’: No such file or directory
```
Да, это не принципиально, можно вручную устанавливать зависимости. Ну удалили хотя бы нерабоичий сприпт.

**Comment by vmpartner** [comment]
Спасибо за сообщение, проверю

пт, 27 нояб. 2020 г., 14:30 abicorios <notifications@github.com>:
