### ISSUE TITLE
При запуске нет доступа к bitrixsetup.php

### ISSUE THREAD

**Issue by Nikitoz78** [bitrixdock/bitrixdock#92]
Warning: file_put_contents(/var/www/bitrix/bitrixsetup.update): failed to open stream: Permission denied in /var/www/bitrix/bitrixsetup.php on line 381
Даже установка прав 777 на bitrixsetup.php не решает проблему.
Плюс не предусмотрено создание группы www-data при установке на чистую систему.

**Comment by Nikitoz78** [comment]
Сам открыл, сам закрываю:
1. На чистой системе необходимо добавит пользователя и группу www-data
$ useradd www-data
2. Изменить chown -R root:www-data www/ на chown -R www-data:www-data www/

**Comment by wokalek** [comment]
Не помогает
