### ISSUE TITLE
ЧПУ mod_rewrite

### ISSUE THREAD

**Issue by AlexanderDronkin** [bitrixdock/bitrixdock#93]
ЧПУ под апачем не работает по двум причинам, оно отключено в конфиге)) и директория сайта имеет в себе /bitrix/, из-за чего не работает проверка RewriteCond %{REQUEST_FILENAME} !/bitrix/ в .htaccess

**Comment by nikolays93** [comment]
Подскажите, как решить эту проблему? мб "pull request" пильнёте?

**Comment by nikolays93** [comment]
> ЧПУ под апачем не работает по двум причинам, оно отключено в конфиге))

Это вы о <Directory "/var/www/bitrix/"> AllowOverride None?

> не работает проверка RewriteCond %{REQUEST_FILENAME} !/bitrix/ в .htaccess

Нашел в конфиге пары сайтов только RewriteCond %{REQUEST_FILENAME} !/bitrix/urlrewrite.php$ - вроде не мешает.
